# Project 5 – What would it take to Meet the Paris Agreement Energy Production Targets? 

* Student name: Greg Osborne
* Student pace: self paced / part time
* Scheduled project review date/time: 5/1/23
* Instructor name: Morgan Jones
* Blog post URL: https://medium.com/@gregosborne

# Business Understanding
## Stakeholder: [Intergovernmental Panel on Climate Change (IPCC)](https://www.ipcc.ch/)

## Background: 
In 1988, NASA scientist Dr. James E. Hansen gave the US Senate, and the world, an [alarming wake-up call](https://www.nytimes.com/1988/06/24/us/global-warming-has-begun-expert-tells-senate.html?unlocked_article_code=7ICo0v4G5DKBY6-D1ldNLgeAT9vW_mDX1QXS8YQ8i1YFIU3stRPnNlVeQRegb-Zc5QG0yg7---7z0LuWRErszApcfFFpSdunINDInNkKoPpmCGDsElX6EOXI963OLfCmiSP6MPB4lKdmpCf3W9Ve7rFqSTD3bYd96NP8PKQ0a__Rs9AjVg0q_hN9pOYvl9FaFvAZk4_GB5-5ZyNAxz2_IbnUa9dPvBTycXkSYL8VuS8MgKwm3cEHj-vX-wKf4zbdL-4JZOmApEIzpkAL8sfjzMNsTREmHooyk181rQmVZ9hwp-Oe_auNvXX2rNwt2YLRGQCTo2G9l5mAAc6on7ZwxJZ2pX8tARc9TlgguMB7nMIM&smid=url-share). Dr. Hansen told Senators that *The Greenhouse Effect* was not a threat of the far future, but a reality that had made the first five months of that year the hottest on record since measurements began 130 years earlier. Natural cycles of the Earth's atmosphere did not create the heat, pollution did, specifically Greenhouse Gas (GHG) emissions. [Alarmed](https://unfoundation.org/blog/post/the-historic-1988-senate-climate-hearing-30-years-later/#:~:text=At%20this%20hearing%20in%201988,manage%20and%20mitigate%20their%20impacts.), the UN created the Intergovernmental Panel on Climate Change (IPCC), a global body of scientists who review the best studies on the causes and effects of climate change and summarizes the information for the world's national leaders.

Despite the warning and efforts of the IPCC, the world continued to pump out greenhouse gases. [More than half of all carbon dioxide (CO2) emissions emitted by mankind](https://ieep.eu/news/more-than-half-of-all-co2-emissions-since-1751-emitted-in-the-last-30-years/) occurred since that fateful Senate hearing, even as scientists have learned more about the [dangers](https://www.nytimes.com/2015/06/23/science/risk-of-extreme-weather-from-climate-change-to-rise-over-next-century-report-says.html?unlocked_article_code=DSbwaXvX1OQ_GAzkANKHgMQlmUKI4erOh8WNwN8TGr_qf_LdjxBKsVdlgKsF6IN9RFD2DRxek1GIpO8tY8sVmL0XlDQqwxrlyH1Y-giQ9VrIvJdQdqPdoA8BJ-DnQrFrheUhWsOwDncXPziIX7xTGWv_uZahjAg7SOzyqrVe4BRHdDrU_jJsOW3cE1fxwKJya8UKUMmheMX7QOR0jKLRORr8BQat0CJFbU0n23pdmo62mW-qhlWIyzTy-rEHDpcT9Aj3WBM6O9jdFoa348cW5OD-TNc0P8YTvMzCsQ0Hm7lmyEnXK-gRcvK-6ShKaqS_q_RcTuayoz4ipMzxtlLZhHDkIYELZWu6vURF3ddIXKyDkXVDx84w40x6G1V95wSCyx88rtxDYIUIBPwVNhInII_MmrokhNp_fz9S&smid=url-share) the crisis brings to humanity, and how much worse it will be in the future.

To encourage nations to change, the UN held the 2015 United Nations Climate Change Conference near Paris. 195 nations, along with the European Union came to participate. Protests were banned, so people [laid out their shoes to show their presence](https://www.usatoday.com/story/news/nation-now/2015/11/30/lines-empty-shoes-send-powerful-message-paris/76572552/). Days of negotiations took place, but the nations reached a consensus on December 12, 2015. The historic [Paris Agreement](https://apnews.com/article/climate-climate-change-john-kerry-paris-archive-81dabae32cb8463b86bd85d762da9e6d) legally bound the nations of the world to limit global warming to well below 2 °C (3.6 °F) over preindustrial levels. 

The Paris Agreement also commissioned the IPCC to review the effects of climate change at 1.5 °C (2.7 °F). [The IPCC released a report in 2018](https://www.ipcc.ch/sr15/chapter/spm/), detailing the pestilence of a warmer world. These horrors are beyond the scope of this analysis, but one of the more alarming discoveries is that warming will cause coral bleaching of 80% of the world's coral reefs, a major food source of the world's oceans. The report led to the [largest climate protest in history](https://www.forbes.com/sites/ceciliarodriguez/2019/09/21/biggest-ever-climate-protest-in-photos-greta-thunberg-and-the-worlds-youth-demand-action/?sh=63a91c08ab4d). People in the streets demanded their governments protect the future by making investments and passing policies to cut GHG emissions. 

Sadly, even with drastic cuts to emissions, it is unlikely the average temperature will stay lower than 1.5 °C over pre-industrial levels. As alarming as that is, going beyond 1.5 °C would be even worse. 

## Problem: 

To limit climate change to no greater than 1.5 °C over pre-industrial levels, the IPCC's 2018 special report concluded that GHG emissions must ["decline by about 45% from 2010 levels by 2030 (40–60% interquartile range), reaching net zero around 2050."](https://www.ipcc.ch/sr15/chapter/spm/#article-spm-c) Today, in 2023, we are [already at 1.1 °C (2 °F)](https://earthobservatory.nasa.gov/world-of-change/global-temperatures). With GHG emissions as they are, scientists anticipate this average to grow by about 0.2 °C per decade unless GHG emissions are cut.

The IPCC needs to know if nations are on track to cut their GHG emissions within the proposed time frame. If countries are not meeting their targets, the IPCC needs to educate them on how to cut GHG emissions as soon as possible.

GHG emissions occur in multiple sectors of the economy. Accounting for emissions across all sectors is beyond the scope of this report. Instead, I will analyze how electricity generation can meet the reduction targets set by the IPCC in 2018. Electricity generation refers to power plants creating electricity to distribute across power lines to residential and business locations. Electricity sources include fossil fuel methods that emit GHG and sources that do not emit GHG, like nuclear power and renewables. Fossil fuel sources include burning coal, oil, and natural gas, while renewables include wind turbines, solar panels, and hydroelectrical. Nuclear energy is not considered renewable but is GHG emission-free. Since electricity generation contributes to [about 40% of all global emissions](https://www.iea.org/data-and-statistics/charts/global-energy-related-co2-emissions-by-sector), reducing its GHG emissions will potentially be larger than reducing emissions in any other sector.

## Time-Series Modeling

This analysis requires projecting multiple considerations into the future. These include the following:

**1. Increase in Electricity Demand**

In addition to continued development in emerging economies, giving their population greater access to electricity, the world's demand for electricity will rise as we cut emissions across all sectors. The poster-child example of this is the automobile. Car manufacturers making up a quarter of global sales have pledged to [cease production of internal-combustion-engine cars](https://www.caranddriver.com/news/a38213848/automakers-pledge-end-gas-sales-2040/) within the IPCC's timeline. Therefore, electricity will power a larger portion of society's small-distance transportation needs than ever before, creating greater demand.

**2. Construction Rate of Clean Power Generation**

Contrary to what the crisis needs, we cannot build a billion wind turbines overnight. We can only build clean energy sources as materials, labor availability, construction time, and politics allow. These factors can be changed as time moves forward, but they must be considered as part of this analysis.

**3. Construction Rate of GHG Power Generation**

Unfortunately, not only are fossil fuels still powering our lifestyles, but several coal-fired power plants are scheduled to be [built in the future](https://www.reuters.com/business/energy/cop26-aims-banish-coal-asia-is-building-hundreds-power-plants-burn-it-2021-10-29/). This analysis must consider the growth of coal power as well.

**4. Average Global Temperature**

This analysis will primarily focus on electricity generation, which is not the only source of GHG emissions. This analysis will also project the rise of global temperature with the proposed changes to electricity generation, and with assumptions across other economic sectors, both business-as-usual and sufficient GHG reduction scenarios.

With all these factors, time-series modeling can assist with projection needs. This project will show the global average temperature with current trends, and propose scenarios for how to get back on track.

## Methodology

The target of the Paris Agreement is a temperature. Rather than set specific emissions goals for certain chemicals, the Paris agreement legally binds nations to limit global warming to well below 2 °C (3.6 °F) over preindustrial levels, ideally 1.5 °C (2.7 °F). The first model will look at all of the natural and man-made factors that influence Earth's average annual temperature and estimate the temperature based on their Effective Radiative Forcing, which is itself a conversion from their concentration in the atmosphere. This will be detailed more later.

The two primary factors that determine the earth's annual temperature are GHG emissions, and GHG already in the atmosphere. GHG emissions are measured in weight emitted into the atmosphere, and the GHG already in the atmosphere is measured in parts per million, billion or trillion. I convert the estimates between GHG emitted to GHG in the atmosphere. To do this, I will create a second time series model with a dependent variable of atmospheric concentration of Greenhouse Gases based on the cumulative and annual total of GHG emitted. 

I will then build multiple time series models to project different scenarios of GHG emissions into the future based on estimated energy demands and the methods used to generate that energy. The goal will be to decline the emissions to 45% of 2010 levels for just the electricity generation sector alone.

The planned steps I will follow for this project include: 

1. Create a time series model with a target of annual global temperature rise over pre-industrial levels from 1880–2019.The input will be all effective radiative forcing substances in the atmosphere as given by the IPCC. The target data will be Nasa's record of the annual global temperature.
2. Create a model that predicts GHG atmospheric concentrations based on that year's GHG emissions and the cumulative emissions mankind has released into the atmosphere. The primary data to use for the model, with a target of temperature, is the [PRIMAP-hist national historical emissions time series](https://zenodo.org/record/7727475#.ZC73QXbMK3A). I will cull a lot of the superfluous data.
3. The above data does not distinguish between electricity generation, transportation, and industrial processes. So, I will use the [BP](https://www.bp.com/en/global/corporate/energy-economics/statistical-review-of-world-energy.html) data to estimate CO2-equivalent (CO2e) emissions for power generation for the relevant years. I will then split 1A, Fuel combustion activities, into two separate entities, 1A.1: Energy Industries and 1A.5: Non-specified. Certainly, a bulk of the unspecified category is actually transportation and industry, but defining that is not part of this analysis.
4. Project the model to 2050 based on the estimated rise in energy demand and an estimated rise in the other economic sectors.
5. Through a process of trial and error, figure out how to make the best cuts that are necessary to meet the 45% target by 2030, and then the 0% target by 2050. 
6. Finally, see if the proposed changes combined with other estimated mitigations from other industries in the world will be enough to keep the world below 1.5 °C (2.7 °F).

# Data Sources

## Average Global Temperature Stats
* **IPCC Working Group 1 Assessment Report 6**
  * **Chapter 2 | Changing State of the Climate System**: [Report](https://www.ipcc.ch/report/ar6/wg1/downloads/report/IPCC_AR6_WGI_Chapter02.pdf)
    * Figure 2.11 | Annual average global land-ocean surface temperature from 1850–2020 plus or minus the average from 1850–1900 in °C:
      * [IPCC Report, Page 316](https://www.ipcc.ch/report/ar6/wg1/downloads/report/IPCC_AR6_WGI_Chapter02.pdf#page=30), [Figure](https://www.ipcc.ch/report/ar6/wg1/figures/chapter-2/figure-2-11), [References, Page 19](https://www.ipcc.ch/report/ar6/wg1/downloads/report/IPCC_AR6_WGI_Chapter02_SM.pdf#page=19), [Dataset](https://dap.ceda.ac.uk/badc/ar6_wg1/data/ch_02/ch2_fig11/v20211207/Figure_2_11c-lower_panel.csv) (Four datasets. The IPCC averages all four together to create Figure 2.11)


**Unused (maybe)**
* Annual average global land-ocean surface temperature from 1880–2022 compared to the long-term average from 1951–1980. [NASA](https://climate.nasa.gov/vital-signs/global-temperature/), [Dataset](https://data.giss.nasa.gov/gistemp/graphs/graph_data/Global_Mean_Estimates_based_on_Land_and_Ocean_Data/graph.txt)
* A brilliant graphic from Bloomberg from back in 1995. Possibly update it? Project it towards the future? [Bloomberg](https://www.bloomberg.com/graphics/2015-whats-warming-the-world/) (Multiple datasets and links in this article)

## Atmospheric Greenhouse Gas Concentrations
* **IPCC Working Group 1 Assessment Report 6**
  * **Chapter 7 | The Earth’s Energy Budget, Climate Feedbacks and Climate Sensitivity**: [Report](https://www.ipcc.ch/report/ar6/wg1/downloads/report/IPCC_AR6_WGI_Chapter07.pdf)
    * 7.SM Chapter 7: The Earth’s energy budget, climate feedbacks, 3 and climate sensitivity - Supplementary Material: [Report](https://www.ipcc.ch/report/ar6/wg1/downloads/report/IPCC_AR6_WGI_FGD_Chapter07_SM.pdf)
      * Table 7.SM.1 | Simplified expressions to compute radiative forcing (RF) from concentrations of greenhouse gases: [Report, Page 3](https://www.ipcc.ch/report/ar6/wg1/downloads/report/IPCC_AR6_WGI_FGD_Chapter07_SM.pdf#page=3)
      * Table 7.SM.7 | Metrics for greenhouse gases: [Report, Page 24](https://www.ipcc.ch/report/ar6/wg1/downloads/report/IPCC_AR6_WGI_FGD_Chapter07_SM.pdf#page=24). 
       * [CSV of table on Github](https://github.com/IPCC-WG1/Chapter-7/blob/main/data_output/7sm/metrics_supplement_cleaned.csv) The author's note in the project's [GitHub](https://github.com/IPCC-WG1/Chapter-7/) that the published table has two typos, corrected in this linked table.
  * **Annex III | Tables of Historical and Projected Well-mixed Greenhouse Gas Mixing Ratios and Effective Radiative Forcing of All Climate Forcers**: [Report](https://www.ipcc.ch/report/ar6/wg1/downloads/report/IPCC_AR6_WGI_AnnexIII.pdf)
    * IPCC 2021 WG1 AR6 Annex III Extended Data depository: [IPCC](https://zenodo.org/record/5705391#.ZDHn1HbMK3A)
    * Table AIII.1 | Historical abundances of all GHG: [IPCC](https://zenodo.org/record/5705391/files/table_A3.1_historical_abundances.csv)
    * Table AIII.2 | Future abundances of GHG for nine SSP scenarios (2020–2500): [Meinshausen](https://greenhousegases.science.unimelb.edu.au/img/SUPPLEMENT_DataTables_Meinshausen_6May2020.xlsx)
    * Table AIII.3 | Effective radiative forcing (W m$^{-2}$) time series of all climate forcers from 1750–2019: [IPCC](https://zenodo.org/record/5705391/files/table_A3.3_historical_ERF_1750-2019_best_estimate.csv)
     * Minor GHG breakdown: [IPCC](https://zenodo.org/record/5705391/files/table_A3.3_historical_ERF_1750-2019_minorGHG_breakdown.csv)
    * Table AIII.4 | Effective radiative forcing (W m$^{-2}$) time series of all climate forcers for nine SSP scenarios (2020–2500): [IPCC](https://zenodo.org/record/5705391#.ZDHn1HbMK3A) 
     * (Currently, this just links back to the full depository. I'll need to make decisions later about what SSP scenarios to compare my projections to)

**Level-Up: Possibly add historic data to make up for the missing years of 2020-2022, the pandemic years.**
* NOAA's historic atmospheric concentration data on CO2 from 1979–2022: [NOAA](https://gml.noaa.gov/webdata/ccgg/trends/co2/co2_annmean_gl.csv)
* NOAA's historic atmospheric concentration data on CH4 from 1984–2022: [NOAA](https://gml.noaa.gov/webdata/ccgg/trends/ch4/ch4_annmean_gl.csv)
* NOAA's historic atmospheric concentration data on N2O from 2001–2022: [NOAA](https://gml.noaa.gov/webdata/ccgg/trends/n2o/n2o_annmean_gl.csv)
* NOAA's historic atmospheric concentration data on SF6 from 1998–2022: [NOAA](https://gml.noaa.gov/webdata/ccgg/trends/sf6/sf6_annmean_gl.csv)
* NOAA's historic atmospheric concentration data of all GHG from 1979–2021: [NOAA](https://gml.noaa.gov/aggi/NOAA_MoleFractions_2022.csv)
* NOAA's historic Annual Greenhouse Gas Index (AGGI) from 1979–2021: [NOAA](https://gml.noaa.gov/aggi/AGGI_Table.csv)
* NOAA's formulas to convert ppm to Effective Radiative Forcing: [NOAA](https://gml.noaa.gov/aggi/aggi.html)
  * I'll only use this in conjunction with other NOAA calculations. Otherwise, I'll use the AR6 formula above.
* NOAA's library of updated measurements, for updating past 2019 (Annual means must be derived from flask samples): [NOAA](https://gml.noaa.gov/hats/combined/N2O.html)


## Greenhouse Gas Emissions
* Historic emissions data by country by sector: [PRIMAP-hist national historical emissions time series](https://zenodo.org/record/7727475#.ZC73QXbMK3A)
  * Key to emissions data: [National Greenhouse Gas Inventory, Page 6](https://www.ipcc-nggip.iges.or.jp/public/2006gl/pdf/0_Overview/V0_1_Overview.pdf#page=6)

**Unused:**
* Various emissions data by country and by source: [Integrated Carbon Observation System](https://data.icos-cp.eu/licence?ids=%5B%22G3ZMktDpI9i7qrCXzk4v5C2Z%22%5D&isColl=true)

## Energy Production / Consumption
* Energy Production Wattage by Country by Source: [Our World In Data](https://ourworldindata.org/grapher/electricity-prod-source-stacked)
  * Original source: [BP](https://www.bp.com/en/global/corporate/energy-economics/statistical-review-of-world-energy.html)
* Historic Electricity Demand by Country: [Our World In Data](https://ourworldindata.org/grapher/electricity-demand?country=USA~GBR~FRA~DEU~IND~BRA)
  * Original source: [BP](https://www.bp.com/en/global/corporate/energy-economics/statistical-review-of-world-energy.html)
* Energy demand projection up until 2050: [IEA](https://www.iea.org/data-and-statistics/data-product/world-energy-outlook-2022-free-dataset)
  * Data sourced from the IEA's World Energy Outlook 2022 Report: [Countries by Region](https://iea.blob.core.windows.net/assets/830fe099-5530-48f2-a7c1-11f35d510983/WorldEnergyOutlook2022.pdf#page=499)

**Unused:**
* Another comprehensive emissions dataset: [Dataset](https://zenodo.org/record/6483002#.ZC8HAXbMK3B)
* The chart and data motherload: [Our World Data](https://ourworldindata.org/energy)
* Energy Consumption Percentage Increases (Will probably go with projections instead): [Our World In Data](https://ourworldindata.org/grapher/change-energy-consumption)
* Death Rates by electricity source [Our World In Data](https://ourworldindata.org/grapher/death-rates-from-energy-production-per-twh)

## Energy kwh to CO2e Conversion Calculations

* **NREL | Life Cycle Greenhouse Gas Emissions from Electricity Generation: Update (2021)**
  * Table 1. Median Published Life Cycle Emissions Factors for Electricity Generation Technologies, by Life Cycle Phase:  [NREL](https://www.nrel.gov/docs/fy21osti/80580.pdf#page=3)
    * "We have updated all previous LCAs to use the latest IPCC assessment report, AR5, which increased the GWP for methane to 30 for sources of fossil origin from 25 in AR4 (28).":
    [Report, Page 4](https://www.pnas.org/doi/epdf/10.1073/pnas.1309334111#page=4)
    * GWP, globalwarming potential harmonized to 100-y IPCC [AR5] values: [Report, Page 5](https://www.pnas.org/doi/epdf/10.1073/pnas.1309334111#page=5)

**Unused:**
* **Climate Change 2014 | Mitigation of Climate Change | Working Group III | Contribution to the Fifth Assessment Report of the IPCC**
  * Table A.III.2 | Emissions of selected electricity supply technologies (gCO2eq/kWh):  [IPCC report page 7](https://www.ipcc.ch/site/assets/uploads/2018/02/ipcc_wg3_ar5_annex-iii.pdf#page=7)
* **Renewable Energy Sources and Climate Change Mitigation | Special Report of the IPCC**
* An earlier IPCC report with a number on Oil kwh conversions. [IPCC report Figure 9.8, page 732](https://www.ipcc.ch/site/assets/uploads/2018/03/Chapter-9-Renewable-Energy-in-the-Context-of-Sustainable-Development-1.pdf#page=26) & [Table 9.8, page 982](https://www.ipcc.ch/site/assets/uploads/2018/03/Annex-II-Methodology-1.pdf#page=10)
* **IPCC Fourth Assessment Report | Climate Change 2007 | Working Group I | The Physical Science Basis**
  * Table 2.14. Lifetimes, radiative efficiencies and direct (except for CH4) GWPs relative to CO2: [IPCC](https://archive.ipcc.ch/publications_and_data/ar4/wg1/en/ch2s2-10-2.html)

**How I found these values:**
* Some nuclear site that I found the above link from: [Nukes](https://www.world-nuclear.org/information-library/energy-and-the-environment/carbon-dioxide-emissions-from-electricity.aspx)
* US Energy Information's estimate on the same numbers for the USA: [EIA](https://www.eia.gov/tools/faqs/faq.php?id=74&t=11)
* BP of all people has some great data

# Table of Contents

<h1>Project 5 – What would it take to Meet the Paris Agreement Energy Production Targets?<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Project-5-–-What-would-it-take-to-Meet-the-Paris-Agreement-Energy-Production-Targets?" data-toc-modified-id="Project-5-–-What-would-it-take-to-Meet-the-Paris-Agreement-Energy-Production-Targets?-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Project 5 – What would it take to Meet the Paris Agreement Energy Production Targets?</a></span></li><li><span><a href="#Business-Understanding" data-toc-modified-id="Business-Understanding-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Business Understanding</a></span><ul class="toc-item"><li><span><a href="#Stakeholder:-Intergovernmental-Panel-on-Climate-Change-(IPCC)" data-toc-modified-id="Stakeholder:-Intergovernmental-Panel-on-Climate-Change-(IPCC)-2.1"><span class="toc-item-num">2.1&nbsp;&nbsp;</span>Stakeholder: <a href="https://www.ipcc.ch/" target="_blank">Intergovernmental Panel on Climate Change (IPCC)</a></a></span></li><li><span><a href="#Background:" data-toc-modified-id="Background:-2.2"><span class="toc-item-num">2.2&nbsp;&nbsp;</span>Background:</a></span></li><li><span><a href="#Problem:" data-toc-modified-id="Problem:-2.3"><span class="toc-item-num">2.3&nbsp;&nbsp;</span>Problem:</a></span></li><li><span><a href="#Time-Series-Modeling" data-toc-modified-id="Time-Series-Modeling-2.4"><span class="toc-item-num">2.4&nbsp;&nbsp;</span>Time-Series Modeling</a></span></li><li><span><a href="#Methodology" data-toc-modified-id="Methodology-2.5"><span class="toc-item-num">2.5&nbsp;&nbsp;</span>Methodology</a></span></li></ul></li><li><span><a href="#Data-Sources" data-toc-modified-id="Data-Sources-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>Data Sources</a></span><ul class="toc-item"><li><span><a href="#Average-Global-Temperature-Stats" data-toc-modified-id="Average-Global-Temperature-Stats-3.1"><span class="toc-item-num">3.1&nbsp;&nbsp;</span>Average Global Temperature Stats</a></span></li><li><span><a href="#Atmospheric-Greenhouse-Gas-Concentrations" data-toc-modified-id="Atmospheric-Greenhouse-Gas-Concentrations-3.2"><span class="toc-item-num">3.2&nbsp;&nbsp;</span>Atmospheric Greenhouse Gas Concentrations</a></span></li><li><span><a href="#Greenhouse-Gas-Emissions" data-toc-modified-id="Greenhouse-Gas-Emissions-3.3"><span class="toc-item-num">3.3&nbsp;&nbsp;</span>Greenhouse Gas Emissions</a></span></li><li><span><a href="#Energy-Production-/-Consumption" data-toc-modified-id="Energy-Production-/-Consumption-3.4"><span class="toc-item-num">3.4&nbsp;&nbsp;</span>Energy Production / Consumption</a></span></li><li><span><a href="#Energy-kwh-to-CO2e-Conversion-Calculations" data-toc-modified-id="Energy-kwh-to-CO2e-Conversion-Calculations-3.5"><span class="toc-item-num">3.5&nbsp;&nbsp;</span>Energy kwh to CO2e Conversion Calculations</a></span></li></ul></li><li><span><a href="#Table-of-Contents" data-toc-modified-id="Table-of-Contents-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>Table of Contents</a></span></li><li><span><a href="#Python-Libraries" data-toc-modified-id="Python-Libraries-5"><span class="toc-item-num">5&nbsp;&nbsp;</span>Python Libraries</a></span></li><li><span><a href="#Data-Cleaning" data-toc-modified-id="Data-Cleaning-6"><span class="toc-item-num">6&nbsp;&nbsp;</span>Data Cleaning</a></span><ul class="toc-item"><li><span><a href="#Loading-the-Data" data-toc-modified-id="Loading-the-Data-6.1"><span class="toc-item-num">6.1&nbsp;&nbsp;</span>Loading the Data</a></span><ul class="toc-item"><li><span><a href="#Global-Temperature" data-toc-modified-id="Global-Temperature-6.1.1"><span class="toc-item-num">6.1.1&nbsp;&nbsp;</span>Global Temperature</a></span></li><li><span><a href="#GHG-Atmospheric-Concentration" data-toc-modified-id="GHG-Atmospheric-Concentration-6.1.2"><span class="toc-item-num">6.1.2&nbsp;&nbsp;</span>GHG Atmospheric Concentration</a></span><ul class="toc-item"><li><span><a href="#Metrcs-for-GHG" data-toc-modified-id="Metrcs-for-GHG-6.1.2.1"><span class="toc-item-num">6.1.2.1&nbsp;&nbsp;</span>Metrcs for GHG</a></span></li><li><span><a href="#Historical-GHG-concentrations" data-toc-modified-id="Historical-GHG-concentrations-6.1.2.2"><span class="toc-item-num">6.1.2.2&nbsp;&nbsp;</span>Historical GHG concentrations</a></span></li><li><span><a href="#GHG-projections" data-toc-modified-id="GHG-projections-6.1.2.3"><span class="toc-item-num">6.1.2.3&nbsp;&nbsp;</span>GHG projections</a></span></li><li><span><a href="#Effective-Radiative-Forcing-All-Climate-Factors" data-toc-modified-id="Effective-Radiative-Forcing-All-Climate-Factors-6.1.2.4"><span class="toc-item-num">6.1.2.4&nbsp;&nbsp;</span>Effective Radiative Forcing All Climate Factors</a></span></li><li><span><a href="#Minor-GHG-Breakdon-for-the-Same-Time-Series-Model" data-toc-modified-id="Minor-GHG-Breakdon-for-the-Same-Time-Series-Model-6.1.2.5"><span class="toc-item-num">6.1.2.5&nbsp;&nbsp;</span>Minor GHG Breakdon for the Same Time Series Model</a></span></li><li><span><a href="#Effective-Radiative-Forcing-Projection" data-toc-modified-id="Effective-Radiative-Forcing-Projection-6.1.2.6"><span class="toc-item-num">6.1.2.6&nbsp;&nbsp;</span>Effective Radiative Forcing Projection</a></span></li></ul></li><li><span><a href="#Greenhouse-Gas-Emissions" data-toc-modified-id="Greenhouse-Gas-Emissions-6.1.3"><span class="toc-item-num">6.1.3&nbsp;&nbsp;</span>Greenhouse Gas Emissions</a></span><ul class="toc-item"><li><span><a href="#Historical-emissions" data-toc-modified-id="Historical-emissions-6.1.3.1"><span class="toc-item-num">6.1.3.1&nbsp;&nbsp;</span>Historical emissions</a></span></li></ul></li><li><span><a href="#Energy-Production-/-Consumption" data-toc-modified-id="Energy-Production-/-Consumption-6.1.4"><span class="toc-item-num">6.1.4&nbsp;&nbsp;</span>Energy Production / Consumption</a></span><ul class="toc-item"><li><span><a href="#Historic-Electricity-Demand-by-Country" data-toc-modified-id="Historic-Electricity-Demand-by-Country-6.1.4.1"><span class="toc-item-num">6.1.4.1&nbsp;&nbsp;</span>Historic Electricity Demand by Country</a></span></li><li><span><a href="#Energy-Demand-Projection" data-toc-modified-id="Energy-Demand-Projection-6.1.4.2"><span class="toc-item-num">6.1.4.2&nbsp;&nbsp;</span>Energy Demand Projection</a></span></li><li><span><a href="#Energy-Generation" data-toc-modified-id="Energy-Generation-6.1.4.3"><span class="toc-item-num">6.1.4.3&nbsp;&nbsp;</span>Energy Generation</a></span></li></ul></li><li><span><a href="#Value-counts" data-toc-modified-id="Value-counts-6.1.5"><span class="toc-item-num">6.1.5&nbsp;&nbsp;</span>Value counts</a></span></li><li><span><a href="#Rename-Columns" data-toc-modified-id="Rename-Columns-6.1.6"><span class="toc-item-num">6.1.6&nbsp;&nbsp;</span>Rename Columns</a></span><ul class="toc-item"><li><span><a href="#Renaming-df_deg_c" data-toc-modified-id="Renaming-df_deg_c-6.1.6.1"><span class="toc-item-num">6.1.6.1&nbsp;&nbsp;</span>Renaming df_deg_c</a></span></li><li><span><a href="#Renaming-df_hist_ghg" data-toc-modified-id="Renaming-df_hist_ghg-6.1.6.2"><span class="toc-item-num">6.1.6.2&nbsp;&nbsp;</span>Renaming df_hist_ghg</a></span></li><li><span><a href="#Renaming-df_proj_ghg" data-toc-modified-id="Renaming-df_proj_ghg-6.1.6.3"><span class="toc-item-num">6.1.6.3&nbsp;&nbsp;</span>Renaming df_proj_ghg</a></span></li><li><span><a href="#Renaming-df_hist_rf" data-toc-modified-id="Renaming-df_hist_rf-6.1.6.4"><span class="toc-item-num">6.1.6.4&nbsp;&nbsp;</span>Renaming df_hist_rf</a></span></li><li><span><a href="#Renaming-df_emissions" data-toc-modified-id="Renaming-df_emissions-6.1.6.5"><span class="toc-item-num">6.1.6.5&nbsp;&nbsp;</span>Renaming df_emissions</a></span></li><li><span><a href="#Renaming-df_electricity" data-toc-modified-id="Renaming-df_electricity-6.1.6.6"><span class="toc-item-num">6.1.6.6&nbsp;&nbsp;</span>Renaming df_electricity</a></span></li><li><span><a href="#Renaming-df_projected_demand" data-toc-modified-id="Renaming-df_projected_demand-6.1.6.7"><span class="toc-item-num">6.1.6.7&nbsp;&nbsp;</span>Renaming df_projected_demand</a></span></li></ul></li><li><span><a href="#Visualize-the-quantities-of-the-data." data-toc-modified-id="Visualize-the-quantities-of-the-data.-6.1.7"><span class="toc-item-num">6.1.7&nbsp;&nbsp;</span>Visualize the quantities of the data.</a></span></li></ul></li><li><span><a href="#Preparing-Data-For-Analysis" data-toc-modified-id="Preparing-Data-For-Analysis-6.2"><span class="toc-item-num">6.2&nbsp;&nbsp;</span>Preparing Data For Analysis</a></span><ul class="toc-item"><li><span><a href="#Testing-for-bad-data" data-toc-modified-id="Testing-for-bad-data-6.2.1"><span class="toc-item-num">6.2.1&nbsp;&nbsp;</span>Testing for bad data</a></span></li></ul></li><li><span><a href="#Frequency-Distributions" data-toc-modified-id="Frequency-Distributions-6.3"><span class="toc-item-num">6.3&nbsp;&nbsp;</span>Frequency Distributions</a></span></li></ul></li><li><span><a href="#Building-Models" data-toc-modified-id="Building-Models-7"><span class="toc-item-num">7&nbsp;&nbsp;</span>Building Models</a></span><ul class="toc-item"><li><span><a href="#Final-Model-Selection" data-toc-modified-id="Final-Model-Selection-7.1"><span class="toc-item-num">7.1&nbsp;&nbsp;</span>Final Model Selection</a></span></li></ul></li><li><span><a href="#Tuning-Models" data-toc-modified-id="Tuning-Models-8"><span class="toc-item-num">8&nbsp;&nbsp;</span>Tuning Models</a></span></li><li><span><a href="#Final-Model-And-Analysis" data-toc-modified-id="Final-Model-And-Analysis-9"><span class="toc-item-num">9&nbsp;&nbsp;</span>Final Model And Analysis</a></span></li><li><span><a href="#Conclusion" data-toc-modified-id="Conclusion-10"><span class="toc-item-num">10&nbsp;&nbsp;</span>Conclusion</a></span><ul class="toc-item"><li><span><a href="#Limitations-of-Scope-/-Provided-Data" data-toc-modified-id="Limitations-of-Scope-/-Provided-Data-10.1"><span class="toc-item-num">10.1&nbsp;&nbsp;</span>Limitations of Scope / Provided Data</a></span></li><li><span><a href="#Future-Research-Opportunities" data-toc-modified-id="Future-Research-Opportunities-10.2"><span class="toc-item-num">10.2&nbsp;&nbsp;</span>Future Research Opportunities</a></span></li><li><span><a href="#Recommendations" data-toc-modified-id="Recommendations-10.3"><span class="toc-item-num">10.3&nbsp;&nbsp;</span>Recommendations</a></span></li><li><span><a href="#Grading" data-toc-modified-id="Grading-10.4"><span class="toc-item-num">10.4&nbsp;&nbsp;</span>Grading</a></span><ul class="toc-item"><li><span><a href="#Attention-to-Detail" data-toc-modified-id="Attention-to-Detail-10.4.1"><span class="toc-item-num">10.4.1&nbsp;&nbsp;</span>Attention to Detail</a></span><ul class="toc-item"><li><span><a href="#Exceeds-Objective" data-toc-modified-id="Exceeds-Objective-10.4.1.1"><span class="toc-item-num">10.4.1.1&nbsp;&nbsp;</span>Exceeds Objective</a></span></li><li><span><a href="#Meets-Objective-(Passing-Bar)" data-toc-modified-id="Meets-Objective-(Passing-Bar)-10.4.1.2"><span class="toc-item-num">10.4.1.2&nbsp;&nbsp;</span>Meets Objective (Passing Bar)</a></span></li></ul></li><li><span><a href="#Project-Motivation" data-toc-modified-id="Project-Motivation-10.4.2"><span class="toc-item-num">10.4.2&nbsp;&nbsp;</span>Project Motivation</a></span><ul class="toc-item"><li><span><a href="#Exceeds-Objective" data-toc-modified-id="Exceeds-Objective-10.4.2.1"><span class="toc-item-num">10.4.2.1&nbsp;&nbsp;</span>Exceeds Objective</a></span></li><li><span><a href="#Meets-Objective-(Passing-Bar)" data-toc-modified-id="Meets-Objective-(Passing-Bar)-10.4.2.2"><span class="toc-item-num">10.4.2.2&nbsp;&nbsp;</span>Meets Objective (Passing Bar)</a></span></li></ul></li><li><span><a href="#Independent-Learning" data-toc-modified-id="Independent-Learning-10.4.3"><span class="toc-item-num">10.4.3&nbsp;&nbsp;</span>Independent Learning</a></span><ul class="toc-item"><li><span><a href="#Exceeds-Objective" data-toc-modified-id="Exceeds-Objective-10.4.3.1"><span class="toc-item-num">10.4.3.1&nbsp;&nbsp;</span>Exceeds Objective</a></span></li><li><span><a href="#Meets-Objective-(Passing-Bar)" data-toc-modified-id="Meets-Objective-(Passing-Bar)-10.4.3.2"><span class="toc-item-num">10.4.3.2&nbsp;&nbsp;</span>Meets Objective (Passing Bar)</a></span></li></ul></li><li><span><a href="#Reproducibility" data-toc-modified-id="Reproducibility-10.4.4"><span class="toc-item-num">10.4.4&nbsp;&nbsp;</span>Reproducibility</a></span><ul class="toc-item"><li><span><a href="#Exceeds-Objective" data-toc-modified-id="Exceeds-Objective-10.4.4.1"><span class="toc-item-num">10.4.4.1&nbsp;&nbsp;</span>Exceeds Objective</a></span></li><li><span><a href="#Meets-Objective-(Passing-Bar)" data-toc-modified-id="Meets-Objective-(Passing-Bar)-10.4.4.2"><span class="toc-item-num">10.4.4.2&nbsp;&nbsp;</span>Meets Objective (Passing Bar)</a></span></li></ul></li><li><span><a href="#Legacy-Data-Sources" data-toc-modified-id="Legacy-Data-Sources-10.4.5"><span class="toc-item-num">10.4.5&nbsp;&nbsp;</span>Legacy Data Sources</a></span><ul class="toc-item"><li><span><a href="#Disaster-Stats" data-toc-modified-id="Disaster-Stats-10.4.5.1"><span class="toc-item-num">10.4.5.1&nbsp;&nbsp;</span>Disaster Stats</a></span></li><li><span><a href="#Refugee-Stats" data-toc-modified-id="Refugee-Stats-10.4.5.2"><span class="toc-item-num">10.4.5.2&nbsp;&nbsp;</span>Refugee Stats</a></span></li><li><span><a href="#Population-Stats" data-toc-modified-id="Population-Stats-10.4.5.3"><span class="toc-item-num">10.4.5.3&nbsp;&nbsp;</span>Population Stats</a></span></li><li><span><a href="#GDP-Stats" data-toc-modified-id="GDP-Stats-10.4.5.4"><span class="toc-item-num">10.4.5.4&nbsp;&nbsp;</span>GDP Stats</a></span></li><li><span><a href="#At-Risk-Property-Stats" data-toc-modified-id="At-Risk-Property-Stats-10.4.5.5"><span class="toc-item-num">10.4.5.5&nbsp;&nbsp;</span>At-Risk Property Stats</a></span></li><li><span><a href="#Food-Production" data-toc-modified-id="Food-Production-10.4.5.6"><span class="toc-item-num">10.4.5.6&nbsp;&nbsp;</span>Food Production</a></span></li><li><span><a href="#The-2030-target,-keeping-with-the-Paris-Agreement" data-toc-modified-id="The-2030-target,-keeping-with-the-Paris-Agreement-10.4.5.7"><span class="toc-item-num">10.4.5.7&nbsp;&nbsp;</span>The 2030 target, keeping with the Paris Agreement</a></span></li></ul></li></ul></li></ul></li><li><span><a href="#Possible-Project-Directions:" data-toc-modified-id="Possible-Project-Directions:-11"><span class="toc-item-num">11&nbsp;&nbsp;</span>Possible Project Directions:</a></span><ul class="toc-item"><li><span><a href="#Show-Potential-Donors-That-The-Financial-Cost-of-Disaster-Mitigation-Efforts-Will-Continue-To-Rise" data-toc-modified-id="Show-Potential-Donors-That-The-Financial-Cost-of-Disaster-Mitigation-Efforts-Will-Continue-To-Rise-11.1"><span class="toc-item-num">11.1&nbsp;&nbsp;</span>Show Potential Donors That The Financial Cost of Disaster Mitigation Efforts Will Continue To Rise</a></span><ul class="toc-item"><li><span><a href="#Stakeholder:-FEMA?-UN-Disaster-Org?-Red-Cross?" data-toc-modified-id="Stakeholder:-FEMA?-UN-Disaster-Org?-Red-Cross?-11.1.1"><span class="toc-item-num">11.1.1&nbsp;&nbsp;</span>Stakeholder: FEMA? UN Disaster Org? Red Cross?</a></span></li></ul></li><li><span><a href="#Illustrate-Climate-Change's-Future-Effects-on-the-Global-Food-Supply" data-toc-modified-id="Illustrate-Climate-Change's-Future-Effects-on-the-Global-Food-Supply-11.2"><span class="toc-item-num">11.2&nbsp;&nbsp;</span>Illustrate Climate Change's Future Effects on the Global Food Supply</a></span><ul class="toc-item"><li><span><a href="#Stakeholder:-Hunger-NGO?-Compassion-International?-Food-For-The-Hungry?" data-toc-modified-id="Stakeholder:-Hunger-NGO?-Compassion-International?-Food-For-The-Hungry?-11.2.1"><span class="toc-item-num">11.2.1&nbsp;&nbsp;</span>Stakeholder: Hunger NGO? Compassion International? Food For The Hungry?</a></span></li></ul></li><li><span><a href="#Refugee-projection-for-the-United-States" data-toc-modified-id="Refugee-projection-for-the-United-States-11.3"><span class="toc-item-num">11.3&nbsp;&nbsp;</span>Refugee projection for the United States</a></span><ul class="toc-item"><li><span><a href="#Stakeholder:-The-Subcommittee-on-Immigration-Integrity,-Security,-and-Enforcement" data-toc-modified-id="Stakeholder:-The-Subcommittee-on-Immigration-Integrity,-Security,-and-Enforcement-11.3.1"><span class="toc-item-num">11.3.1&nbsp;&nbsp;</span>Stakeholder: <a href="https://judiciary.house.gov/subcommittees/committee-judiciary/subcommittee-immigration-integrity-security-and-enforcement" target="_blank">The Subcommittee on Immigration Integrity, Security, and Enforcement</a></a></span></li></ul></li></ul></li></ul></div>

# Python Libraries

In [1]:
# DataFrames and computation
import pandas as pd
import numpy as np

# Graphing
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
#from plotly import graph_objs as go
#from collections import Counter
#import plotly.express as px
#from palettable.colorbrewer.qualitative import Pastel1_7

# Import the Tokenize library
#from nltk.tokenize import RegexpTokenizer

# For Frequency Distributions
#from nltk import FreqDist
#from matplotlib.ticker import MaxNLocator

# For Wordclouds
#from wordcloud import WordCloud
#from wordcloud import ImageColorGenerator

# For stopwords
#import nltk
#from nltk.corpus import stopwords

# For stemming words
#from nltk.stem.snowball import SnowballStemmer

# The Train/Test Split
#from sklearn.model_selection import train_test_split

# Import the TfidfVectorizer class
#from sklearn.feature_extraction.text import TfidfVectorizer

# Bag of Words
#from sklearn.feature_extraction.text import CountVectorizer

# Word2Vec
#import gensim

# For Min/Max Scaling
#from sklearn.preprocessing import MinMaxScaler

# Scores
#from sklearn.model_selection import cross_val_score
#from sklearn.metrics import precision_score, recall_score, accuracy_score
#from sklearn.metrics import f1_score
#from sklearn.metrics import classification_report

# Multinomial Naive Bayes
#from sklearn.naive_bayes import MultinomialNB

# Logistic Regression Model Classifier
#from sklearn.linear_model import LogisticRegression

# Support Vector Machine
#from sklearn import svm

# Random Forest Classifier
#from sklearn.ensemble import RandomForestClassifier

# For XGBoost Classifier
#from xgboost import XGBClassifier

# The Confusion Matrix
#from sklearn.metrics import confusion_matrix
#from sklearn.metrics import ConfusionMatrixDisplay

# For Hyperparameter Tuning
#from sklearn.model_selection import GridSearchCV

# Setting DataFrame Display settings
pd.set_option("display.max_columns", None)

# Formatting decimals to show three numbers after the point.
#pd.options.display.float_format = '{:,.3f}'.format

# Data Cleaning
## Loading the Data


### Global Temperature
* **IPCC Working Group 1 Assessment Report 6**
  * **Chapter 2 | Changing State of the Climate System**: [Report](https://www.ipcc.ch/report/ar6/wg1/downloads/report/IPCC_AR6_WGI_Chapter02.pdf)
    * Figure 2.11 | Annual average global land-ocean surface temperature from 1850–2020 plus or minus the average from 1850–1900 in °C:
      * [IPCC Report, Page 316](https://www.ipcc.ch/report/ar6/wg1/downloads/report/IPCC_AR6_WGI_Chapter02.pdf#page=30), [Figure](https://www.ipcc.ch/report/ar6/wg1/figures/chapter-2/figure-2-11), [References, Page 19](https://www.ipcc.ch/report/ar6/wg1/downloads/report/IPCC_AR6_WGI_Chapter02_SM.pdf#page=19), [Dataset](https://dap.ceda.ac.uk/badc/ar6_wg1/data/ch_02/ch2_fig11/v20211207/Figure_2_11c-lower_panel.csv) (Four datasets. The IPCC averages all four together to create Figure 2.11)

In [2]:
pd.set_option("display.max_rows", 6)
df_deg_c_raw = pd.read_csv(
    "Data/Figure_2_11c-lower_panel.csv",
    encoding='ANSI')
df_deg_c_raw

Unnamed: 0   HadCRUT      NOAA  Berkeley     Kadow  Unnamed: 5  \
0         1850 -0.063333 -0.019804 -0.069216 -0.082353         NaN   
1         1851  0.126667  0.060196  0.000784  0.007647         NaN   
2         1852  0.126667  0.060196  0.040784  0.087647         NaN   
..         ...       ...       ...       ...       ...         ...   
188  1991-2000  0.673667  0.576196  0.699784  0.683647         NaN   
189    2001-10  0.912667  0.801196  0.926784  0.904647         NaN   
190    2011-20  1.115667  1.021196  1.137784  1.087647         NaN   

     HadCRUT confidence limit lower  HadCRUT confidence limit upper  
0                         -0.232701                        0.110388  
1                         -0.055366                        0.301670  
2                         -0.052880                        0.307086  
..                              ...                             ...  
188                             NaN                             NaN  
189                             NaN                             NaN  
190                             NaN                             NaN  

[191 rows x 8 columns]

### GHG Atmospheric Concentration

#### Metrcs for GHG

* Table 7.SM.7 | Metrics for greenhouse gases: [IPCC](https://github.com/IPCC-WG1/Chapter-7/blob/main/data_output/7sm/metrics_supplement_cleaned.csv)

In [3]:
df_metrics_raw = pd.read_csv(
    "Data/metrics_supplement_cleaned.csv",
    encoding='ANSI')
df_metrics_raw

Name          CAS Acronym      Formula  \
0                   Carbon dioxide          =""     NaN          CO2   
1                          Methane          =""     NaN          CH4   
2                    Nitrous oxide          =""     NaN          N2O   
..                             ...          ...     ...          ...   
246   Octamethylcyclotetrasiloxane  ="556-67-2"     NaN   C8H24O4Si4   
247   Decamethylcyclopentasiloxane  ="541-02-6"     NaN  C10H30O5Si5   
248  Dodecamethylcyclohexasiloxane  ="540-97-6"     NaN  C12H36O6Si6   

     Lifetime (yr)  Radiative efficiency (W m-2 ppb-1)  \
0              NaN                            0.000013   
1           11.800                            0.000388   
2          109.000                            0.003200   
..             ...                                 ...   
246          0.027                            0.120000   
247          0.016                            0.098000   
248          0.011                            0.086000   

     AGWP20 (W m-2 yr kg-1)   GWP20  AGWP100 (W m-2 yr kg-1)   GWP100  \
0              2.430000e-14    1.00             8.950000e-14    1.000   
1              1.980000e-12   81.20             2.490000e-12   27.900   
2              6.650000e-12  273.00             2.450000e-11  273.000   
..                      ...     ...                      ...      ...   
246            6.480000e-14    2.66             6.610000e-14    0.739   
247            2.530000e-14    1.04             2.580000e-14    0.289   
248            1.240000e-14    0.51             1.270000e-14    0.142   

     AGWP500 (W m-2 yr kg-1)   GWP500  AGTP50 (K kg-1)    GTP50  \
0               3.140000e-13    1.000     4.280000e-16    1.000   
1               2.500000e-12    7.950     4.730000e-15   11.000   
2               4.070000e-11  130.000     1.240000e-13  290.000   
..                       ...      ...              ...      ...   
246             6.610000e-14    0.211     6.920000e-17    0.162   
247             2.580000e-14    0.082     2.710000e-17    0.063   
248             1.270000e-14    0.040     1.330000e-17    0.031   

     AGTP100 (K kg-1)   GTP100  CGTP50 (yr)  CGTP100 (yr)  
0        3.950000e-16    1.000          0.0           0.0  
1        2.120000e-15    5.380       2730.0        3320.0  
2        9.190000e-14  233.000          0.0           0.0  
..                ...      ...          ...           ...  
246      5.250000e-17    0.133         75.9          89.8  
247      2.050000e-17    0.052         29.7          35.1  
248      1.010000e-17    0.026         14.6          17.2  

[249 rows x 18 columns]

#### Historical GHG concentrations
 * Table AIII.1 | Historical abundances of all GHG: [IPCC](https://zenodo.org/record/5705391/files/table_A3.1_historical_abundances.csv)

In [4]:
df_hist_ghg_raw = pd.read_csv(
    "Data/table_A3.1_historical_abundances.csv",
    encoding='ANSI', header = [36,37])
df_hist_ghg_raw

# UNITS:    ppm     ppb             ppt                                 \
        YYYY    CO2     CH4    N2O HFC-134a HFC-23 HFC-32 HFC-125 HFC-143a   
0     1750.0  278.3   729.2  270.1     0.00   0.00   0.00    0.00     0.00   
1     1850.0  285.5   807.6  272.1     0.00   0.00   0.00    0.00     0.00   
2     1851.0  285.6   807.8  272.2     0.00   0.00   0.00    0.00     0.00   
..       ...    ...     ...    ...      ...    ...    ...     ...      ...   
169   2018.0  407.4  1857.8  331.2   101.84  31.16  16.56   26.31    22.42   
170   2019.0  409.9  1866.3  332.1   107.59  32.41  19.98   29.40    24.01   
171      NaN    NaN     NaN    NaN      NaN    NaN    NaN     NaN      NaN   

                                                                          \
    HFC-152a HFC-227ea HFC-236fa HFC-245fa HFC-365mfc HFC-43-10mee   NF3   
0       0.00      0.00      0.00      0.00       0.00         0.00  0.00   
1       0.00      0.00      0.00      0.00       0.00         0.00  0.00   
2       0.00      0.00      0.00      0.00       0.00         0.00  0.00   
..       ...       ...       ...       ...        ...          ...   ...   
169     7.01      1.46      0.18      2.85       1.04         0.28  1.83   
170     7.13      1.59      0.19      3.06       1.09         0.29  2.05   
171      NaN       NaN       NaN       NaN        NaN          NaN   NaN   

                                                                           \
      SF6 SO2F2    CF4  C2F6  C3F8 c-C4F8  CFC-12  CFC-11 CFC-113 CFC-114   
0    0.00  0.00  34.05  0.00  0.00   0.00    0.00    0.00    0.00    0.00   
1    0.00  0.00  34.05  0.00  0.00   0.00    0.00    0.00    0.00    0.00   
2    0.00  0.00  34.05  0.00  0.00   0.00    0.00    0.00    0.00    0.00   
..    ...   ...    ...   ...   ...    ...     ...     ...     ...     ...   
169  9.59  2.41  84.58  4.76  0.67   1.69  506.97  227.79   70.36   16.00   
170  9.95  2.50  85.48  4.85  0.68   1.75  503.06  226.20   69.80   16.01   
171   NaN   NaN    NaN   NaN   NaN    NaN     NaN     NaN     NaN     NaN   

                                                                            \
    CFC-115 CFC-13 HCFC-22 HCFC-141b HCFC-142b CH3CCl3   CCl4  CH3Cl CH3Br   
0      0.00   0.00    0.00      0.00      0.00    0.00   0.03  457.0  5.30   
1      0.00   0.00    0.00      0.00      0.00    0.00   0.03  457.0  5.30   
2      0.00   0.00    0.00      0.00      0.00    0.00   0.03  457.0  5.30   
..      ...    ...     ...       ...       ...     ...    ...    ...   ...   
169    8.62   3.24  244.04     24.37     22.28    1.90  78.77  551.2  6.57   
170    8.67   3.28  246.76     24.36     22.25    1.62  77.87  550.7  6.49   
171     NaN    NaN     NaN       NaN       NaN     NaN    NaN    NaN   NaN   

                                                  Unnamed: 40_level_0  \
    CH2Cl2 CHCl3 Halon-1211 Halon-1301 Halon-2402             n-C4F10   
0      6.9  4.80       0.00      0.000        0.0                 0.0   
1      6.9  4.80       0.00      0.000        0.0                 0.0   
2      6.9  4.80       0.00      0.000        0.0                 0.0   
..     ...   ...        ...        ...        ...                 ...   
169   39.1  9.37       3.37      3.311        0.4                 NaN   
170   40.6  8.79       3.28      3.322        0.4                 NaN   
171    NaN   NaN        NaN        NaN        NaN                 NaN   

    Unnamed: 41_level_0 Unnamed: 42_level_0 Unnamed: 43_level_0  \
                n-C5F12             n-C6F14             i-C6F14   
0                   0.0                 0.0                 0.0   
1                   0.0                 0.0                 NaN   
2                   0.0                 0.0                 NaN   
..                  ...                 ...                 ...   
169                 NaN                 NaN                 NaN   
170                 NaN                 NaN                 NaN   
171                 NaN  

#### GHG projections
* Table AIII.2 | Future abundances of GHG for nine SSP scenarios (2020–2500): [Meinshausen](https://greenhousegases.science.unimelb.edu.au/img/SUPPLEMENT_DataTables_Meinshausen_6May2020.xlsx)

In [5]:
df_proj_ghg_raw = pd.read_excel(
    "Data/SUPPLEMENT_DataTables_Meinshausen_6May2020.xlsx",
    header = [8,9,10,11], sheet_name = 'T3 - SSP1-1.9 ')
df_proj_ghg_raw

Gas                CO2                                          \
      Unit                ppm                                           
    Region              World Northern Hemisphere Southern Hemisphere   
      Year Unnamed: 1_level_3  Unnamed: 2_level_3  Unnamed: 3_level_3   
0     2015         399.949127          401.678070          398.220184   
1     2016         403.116974          405.106812          401.127106   
2     2017         405.750977          407.749695          403.752228   
..     ...                ...                 ...                 ...   
483   2498         336.895996          336.896118          336.895874   
484   2499         336.873993          336.874115          336.873871   
485   2500         336.863007          336.863129          336.862885   

                   CH4                                          \
                   ppb                                           
                 World Northern Hemisphere Southern Hemisphere   
    Unnamed: 4_level_3  Unnamed: 5_level_3  Unnamed: 6_level_3   
0          1841.955933         1889.736572         1794.175415   
1          1851.593994         1900.575684         1802.612183   
2          1872.668823         1919.833740         1825.503906   
..                 ...                 ...                 ...   
483         871.394897          909.300049          833.489746   
484         871.398926          909.304077          833.493774   
485         871.400879          909.306091          833.495728   

                   N2O                                          \
                   ppb                                           
                 World Northern Hemisphere Southern Hemisphere   
    Unnamed: 7_level_3  Unnamed: 8_level_3  Unnamed: 9_level_3   
0           328.179657          328.476257          327.883026   
1           329.075989          329.363312          328.788635   
2           329.776978          330.064331          329.489624   
..                 ...                 ...                 ...   
483         357.121979          357.409363          356.834595   
484         357.114990          357.402344          356.827606   
485         357.110992          357.398346          356.823608   

                    SF6                                          \
                    ppt                                           
                  World Northern Hemisphere Southern Hemisphere   
    Unnamed: 10_level_3 Unnamed: 11_level_3 Unnamed: 12_level_3   
0              8.568533            8.713426            8.423641   
1              8.884456            9.043184            8.725727   
2              9.175117            9.318385            9.031848   
..                  ...                 ...                 ...   
483           17.688900           17.688900           17.688900   
484           17.683399           17.683399           17.683399   
485           17.680599           17.680599           17.680599   

                    NF3                                          \
                    ppt                                           
                  World Northern Hemisphere Southern Hemisphere   
    Unnamed: 13_level_3 Unnamed: 14_level_3 Unnamed: 15_level_3   
0              1.364862            1.426368            1.303356   
1              1.475920            1.534097            1.417743   
2              1.590270            1.645789            1.534751   
..                  ...                 ...                 ...   
483            2.516450            2.516450            2.516450   
484            2.512010            2.512010            2.512010   
485            2.509800            2.509800            2.509800   

                  SO2F2                                          \
                    ppt                                           
                  World Northern Hemisphere Southern Hemisphere   
    Unnamed: 16_level_3 Unnamed: 17_level_3 Unnamed: 18_level_3   
0    

#### Effective Radiative Forcing All Climate Factors

* Table AIII.3 | Effective radiative forcing (W m$^{-2}$) time series of all climate forcers from 1750–2019: [IPCC](https://zenodo.org/record/5705391/files/table_A3.3_historical_ERF_1750-2019_best_estimate.csv)

In [6]:
df_hist_rf_raw = pd.read_csv(
    "Data/table_A3.3_historical_ERF_1750-2019_best_estimate.csv",
    encoding='ANSI')
df_hist_rf_raw

year       co2       ch4       n2o   other_wmghg        o3  \
0    1750  0.000000  0.000000  0.000000  0.000000e+00  0.000000   
1    1751  0.001416  0.000508  0.000074  7.958010e-10  0.000300   
2    1752  0.002832  0.001016  0.000148  1.591602e-09  0.000600   
..    ...       ...       ...       ...           ...       ...   
267  2017  2.088686  0.537665  0.202033  4.046273e-01  0.459667   
268  2018  2.122080  0.540821  0.205654  4.066049e-01  0.467067   
269  2019  2.156278  0.543983  0.208463  4.080644e-01  0.474467   

     h2o_stratospheric  contrails  aerosol-radiation_interactions  \
0             0.000000   0.000000                        0.000000   
1             0.000047   0.000000                        0.000601   
2             0.000093   0.000000                        0.001247   
..                 ...        ...                             ...   
267           0.049419   0.056725                       -0.211978   
268           0.049709   0.057400                       -0.215540   
269           0.050000   0.057535                       -0.215562   

     aerosol-cloud_interactions  bc_on_snow  land_use  volcanic     solar  \
0                      0.000000    0.000000  0.000000  0.199978  0.097590   
1                      0.004674    0.000017 -0.000229  0.199990  0.079244   
2                      0.007281    0.000035 -0.000458  0.199995  0.049166   
..                          ...         ...       ...       ...       ...   
267                   -0.850840    0.081292 -0.199332  0.150614 -0.017467   
268                   -0.849968    0.080728 -0.199666  0.139917 -0.021468   
269                   -0.842778    0.080000 -0.200000  0.139917 -0.022173   

     nonco2_wmghg   aerosol  chapter2_other_anthro  total_anthropogenic  \
0        0.000000  0.000000               0.000000             0.000000   
1        0.000582  0.005274              -0.000165             0.007408   
2        0.001164  0.008528              -0.000330             0.012794   
..            ...       ...                    ...                  ...   
267      1.144326 -1.062817              -0.011896             2.617965   
268      1.153080 -1.065508              -0.011829             2.664890   
269      1.160510 -1.058340              -0.012465             2.720449   

     total_natural     total  
0         0.297568  0.297568  
1         0.279234  0.286642  
2         0.249161  0.261955  
..             ...       ...  
267       0.133147  2.751112  
268       0.118449  2.783340  
269       0.117744  2.838193  

[270 rows x 20 columns]

#### Minor GHG Breakdon for the Same Time Series Model

* Minor GHG breakdown: [IPCC](https://zenodo.org/record/5705391/files/table_A3.3_historical_ERF_1750-2019_minorGHG_breakdown.csv)

In [7]:
df_hist_rf_minor_raw = pd.read_csv(
    "Data/table_A3.3_historical_ERF_1750-2019_minorGHG_breakdown.csv",
    encoding='ANSI')
df_hist_rf_minor_raw

year  HFC-134a    HFC-23    HFC-32   HFC-125  HFC-143a  HFC-152a  \
0    1750  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
1    1751  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
2    1752  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
..    ...       ...       ...       ...       ...       ...       ...   
267  2017  0.016003  0.005729  0.001577  0.005434  0.003500  0.000694   
268  2018  0.017022  0.005955  0.001845  0.006151  0.003767  0.000714   
269  2019  0.017983  0.006195  0.002227  0.006874  0.004034  0.000726   

     HFC-227ea  HFC-236fa  HFC-245fa  HFC-365mfc  HFC-43-10mee       NF3  \
0     0.000000   0.000000   0.000000    0.000000      0.000000  0.000000   
1     0.000000   0.000000   0.000000    0.000000      0.000000  0.000000   
2     0.000000   0.000000   0.000000    0.000000      0.000000  0.000000   
..         ...        ...        ...         ...           ...       ...   
267   0.000363   0.000042   0.000646    0.000226      0.000097  0.000333   
268   0.000398   0.000045   0.000698    0.000238      0.000100  0.000375   
269   0.000436   0.000048   0.000750    0.000249      0.000103  0.000420   

          SF6     SO2F2       CF4      C2F6      C3F8    c-C4F8    CFC-12  \
0    0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
1    0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
2    0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
..        ...       ...       ...       ...       ...       ...       ...   
267  0.005240  0.000487  0.004890  0.001218  0.000175  0.000509  0.182751   
268  0.005435  0.000507  0.004982  0.001242  0.000180  0.000529  0.181687   
269  0.005638  0.000526  0.005071  0.001265  0.000184  0.000549  0.180285   

       CFC-11   CFC-113   CFC-114   CFC-115    CFC-13   HCFC-22  HCFC-141b  \
0    0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   0.000000   
1    0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   0.000000   
2    0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   0.000000   
..        ...       ...       ...       ...       ...       ...        ...   
267  0.067021  0.021382  0.005030  0.002107  0.000890  0.051546   0.003938   
268  0.066772  0.021209  0.005030  0.002123  0.000899  0.052188   0.003915   
269  0.066307  0.021039  0.005033  0.002136  0.000909  0.052770   0.003914   

     HCFC-142b   CH3CCl3      CCl4     CH3Cl     CH3Br        CH2Cl2  \
0     0.000000  0.000000  0.000000  0.000000  0.000000  0.000000e+00   
1     0.000000  0.000000  0.000000  0.000000  0.000000  7.958010e-10   
2     0.000000  0.000000  0.000000  0.000000  0.000000  1.591602e-09   
..         ...       ...       ...       ...       ...           ...   
267   0.004318  0.000143  0.013224  0.000445  0.000006  9.099840e-04   
268   0.004306  0.000123  0.013085  0.000439  0.000005  9.283965e-04   
269   0.004301  0.000105  0.012935  0.000436  0.000005  9.713820e-04   

        CHCl3  Halon-1211  Halon-1301  Halon-2402  n-C4F10   n-C5F12  \
0    0.000000    0.000000    0.000000    0.000000  0.00000  0.000000   
1    0.000000    0.000000    0.000000    0.000000  0.00000  0.000000   
2    0.000000    0.000000    0.000000    0.000000  0.00000  0.000000   
..        ...         ...         ...         ...      ...       ...   
267  0.000350    0.001038    0.000991    0.000127  0.00007  0.000057   
268  0.000337    0.001011    0.000991    0.000126  0.00007  0.000057   
269  0.000293    0.000983    0.000995    0.000123  0.00007  0.000057   

      n-C6F14   i-C6F14     C7F16     C8F18   CFC-112  CFC-112a  CFC-113a  \
0    0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
1    0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
2    0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
..        ...       ...       ...       ...       ...       ...       ...   
267  0.000099  0.000028  0.000

#### Effective Radiative Forcing Projection

* Table AIII.4 | Effective radiative forcing (W m$^{-2}$) time series of all climate forcers for nine SSP scenarios (2020–2500): [IPCC](https://zenodo.org/record/5705391#.ZDHn1HbMK3A) 
     * (Currently, this just links back to the full depository. I'll need to make decisions later about what SSP scenarios to compare my projections to)

In [8]:
# Will fill this out at a later date.

### Greenhouse Gas Emissions
#### Historical emissions
* Historic emissions data by country by sector: [PRIMAP-hist national historical emissions time series](https://zenodo.org/record/7727475#.ZC73QXbMK3A)
  * Key to emissions data: [National Greenhouse Gas Inventory, Page 6](https://www.ipcc-nggip.iges.or.jp/public/2006gl/pdf/0_Overview/V0_1_Overview.pdf#page=6)

In [9]:
df_emissions_raw = pd.read_csv(
    "Data/PRIMAP-hist_v2.4.2_final_no_rounding_09-Mar-2023.csv",
    encoding='ANSI')
df_emissions_raw

source scenario (PRIMAP-hist) area (ISO3) entity  \
0      PRIMAP-hist_v2.4.2_final_nr                 HISTCR         ABW    CH4   
1      PRIMAP-hist_v2.4.2_final_nr                 HISTCR         ABW    CH4   
2      PRIMAP-hist_v2.4.2_final_nr                 HISTCR         ABW    CH4   
...                            ...                    ...         ...    ...   
36709  PRIMAP-hist_v2.4.2_final_nr                 HISTTP         ZWE    N2O   
36710  PRIMAP-hist_v2.4.2_final_nr                 HISTTP         ZWE    N2O   
36711  PRIMAP-hist_v2.4.2_final_nr                 HISTTP         ZWE    N2O   

                     unit category (IPCC2006_PRIMAP)      1750      1751  \
0      CH4 * gigagram / a                          0  0.012971  0.013068   
1      CH4 * gigagram / a                          1  0.005636  0.005672   
2      CH4 * gigagram / a                        1.A  0.005636  0.005672   
...                   ...                        ...       ...       ...   
36709  N2O * gigagram / a                       M.AG  0.087681  0.089253   
36710  N2O * gigagram / a                   M.AG.ELV  0.086519  0.088070   
36711  N2O * gigagram / a                   M.LULUCF       NaN       NaN   

           1752      1753      1754      1755      1756      1757      1758  \
0      0.013164  0.013260  0.013356  0.013452  0.013548  0.013644  0.013739   
1      0.005708  0.005744  0.005780  0.005816  0.005852  0.005887  0.005922   
2      0.005708  0.005744  0.005780  0.005816  0.005852  0.005887  0.005922   
...         ...       ...       ...       ...       ...       ...       ...   
36709  0.090826  0.092399  0.093971  0.095544  0.097117  0.098690  0.100262   
36710  0.089622  0.091174  0.092726  0.094278  0.095830  0.097382  0.098934   
36711       NaN       NaN       NaN       NaN       NaN       NaN       NaN   

           1759      1760      1761      1762      1763      1764      1765  \
0      0.013834  0.013929  0.014032  0.014134  0.014236  0.014338  0.014440   
1      0.005957  0.005992  0.006030  0.006067  0.006104  0.006141  0.006178   
2      0.005957  0.005992  0.006030  0.006067  0.006104  0.006141  0.006178   
...         ...       ...       ...       ...       ...       ...       ...   
36709  0.101835  0.103408  0.105265  0.107122  0.108979  0.110836  0.112693   
36710  0.100485  0.102037  0.103870  0.105702  0.107535  0.109367  0.111200   
36711       NaN       NaN       NaN       NaN       NaN       NaN       NaN   

           1766      1767      1768      1769      1770      1771      1772  \
0      0.014542  0.014643  0.014745  0.014846  0.014946  0.015055  0.015164   
1      0.006215  0.006251  0.006287  0.006323  0.006359  0.006397  0.006435   
2      0.006215  0.006251  0.006287  0.006323  0.006359  0.006397  0.006435   
...         ...       ...       ...       ...       ...       ...       ...   
36709  0.114550  0.116407  0.118265  0.120122  0.121979  0.124172  0.126365   
36710  0.113032  0.114865  0.116697  0.118530  0.120362  0.122527  0.124691   
36711       NaN       NaN       NaN       NaN       NaN       NaN       NaN   

           1773      1774      1775      1776      1777      1778      1779  \
0      0.015272  0.015380  0.015488  0.015596  0.015703  0.015810  0.015917   
1      0.006473  0.006511  0.006548  0.006586  0.006623  0.006659  0.006696   
2      0.006473  0.006511  0.006548  0.006586  0.006623  0.006659  0.006696   
...         ...       ...       ...       ...       ...       ...       ...   
36709  0.128559  0.130752  0.132946  0.135139  0.137332  0.139526  0.141719   
36710  0.126855  0.129019  0.131184  0.133348  0.135512  0.137677  0.139841   
36711       NaN       NaN       NaN       NaN       NaN       NaN       NaN   

           1780      1781      1782      1783      1784      1785      1786  \
0      0.016024  0.016139  0.016254  0.016368  0.016482  0.016596  0.016710   
1      0.006732  0.006771  0.006810  0.006848  0.006886  0.006924  0.006962   
2      0.

### Energy Production / Consumption
#### Historic Electricity Demand by Country
* Historic Electricity Demand by Country: [Our World In Data](https://ourworldindata.org/grapher/electricity-demand?country=USA~GBR~FRA~DEU~IND~BRA)
  * Original source: [BP](https://www.bp.com/en/global/corporate/energy-economics/statistical-review-of-world-energy.html)

In [10]:
df_historical_demand_raw = pd.read_csv(
    "Data/electricity-demand.csv",
    encoding='ANSI')
df_historical_demand_raw

Entity Code  Year  Electricity demand (TWh)
0     Afghanistan  AFG  2000                      0.57
1     Afghanistan  AFG  2001                      0.69
2     Afghanistan  AFG  2002                      0.79
...           ...  ...   ...                       ...
5567     Zimbabwe  ZWE  2019                      9.35
5568     Zimbabwe  ZWE  2020                      9.58
5569     Zimbabwe  ZWE  2021                      9.79

[5570 rows x 4 columns]

#### Energy Demand Projection
* Energy demand projection until 2050: [IEA](https://www.iea.org/data-and-statistics/data-product/world-energy-outlook-2022-free-dataset)

In [82]:
df_projected_demand_raw = pd.read_csv(
    "Data/IEA-WEO2022_AnnexA_Free_Dataset_Regions.csv",
    encoding='ANSI')
df_projected_demand_raw

PUBLICATION                    SCENARIO  \
0     World Energy Outlook 2022    Stated Policies Scenario   
1     World Energy Outlook 2022    Stated Policies Scenario   
2     World Energy Outlook 2022    Stated Policies Scenario   
3     World Energy Outlook 2022    Stated Policies Scenario   
4     World Energy Outlook 2022    Stated Policies Scenario   
...                         ...                         ...   
2925  World Energy Outlook 2022    Stated Policies Scenario   
2926  World Energy Outlook 2022    Stated Policies Scenario   
2927  World Energy Outlook 2022    Stated Policies Scenario   
2928  World Energy Outlook 2022  Announced Pledges Scenario   
2929  World Energy Outlook 2022  Announced Pledges Scenario   

                        CATEGORY PRODUCT                     FLOW    UNIT  \
0                         Energy   Total      Total energy supply      PJ   
1                         Energy   Total      Total energy supply      PJ   
2                         Energy   Total      Total energy supply      PJ   
3                         Energy   Total      Total energy supply      PJ   
4                         Energy   Total      Total energy supply      PJ   
...                          ...     ...                      ...     ...   
2925  CO2 combustion and process   Total  Total final consumption  Mt CO2   
2926  CO2 combustion and process   Total  Total final consumption  Mt CO2   
2927  CO2 combustion and process   Total  Total final consumption  Mt CO2   
2928  CO2 combustion and process   Total  Total final consumption  Mt CO2   
2929  CO2 combustion and process   Total  Total final consumption  Mt CO2   

              REGION  YEAR     VALUE  
0              World  2010   541.981  
1              World  2020   592.311  
2              World  2021   624.164  
3              World  2030   673.271  
4              World  2050   740.009  
...              ...   ...       ...  
2925  Southeast Asia  2021   933.700  
2926  Southeast Asia  2030  1230.620  
2927  Southeast Asia  2050  1422.280  
2928  Southeast Asia  2030  1081.410  
2929  Southeast Asia  2050   670.950  

[2930 rows x 9 columns]

#### Energy Generation
* Energy Production Wattage by Country by Source: [Our World In Data](https://ourworldindata.org/grapher/electricity-prod-source-stacked)
  * Original source: [BP](https://www.bp.com/en/global/corporate/energy-economics/statistical-review-of-world-energy.html)

In [12]:
df_electricity_raw = pd.read_csv(
    "Data/electricity-prod-source-stacked.csv",
    encoding='ANSI')
df_electricity_raw


Entity Code  Year  \
0      Afghanistan  AFG  2000   
1      Afghanistan  AFG  2001   
2      Afghanistan  AFG  2002   
...            ...  ...   ...   
10646     Zimbabwe  ZWE  2019   
10647     Zimbabwe  ZWE  2020   
10648     Zimbabwe  ZWE  2021   

       Other renewables excluding bioenergy (TWh) (zero filled)  \
0                                                    0.0          
1                                                    0.0          
2                                                    0.0          
...                                                  ...          
10646                                                0.0          
10647                                                0.0          
10648                                                0.0          

       Electricity from bioenergy (TWh) (zero filled)  \
0                                                0.00   
1                                                0.00   
2                                                0.00   
...                                               ...   
10646                                            0.38   
10647                                            0.35   
10648                                            0.38   

       Electricity from solar (TWh)  Electricity from wind (TWh)  \
0                              0.00                          0.0   
1                              0.00                          0.0   
2                              0.00                          0.0   
...                             ...                          ...   
10646                          0.03                          0.0   
10647                          0.03                          0.0   
10648                          0.04                          0.0   

       Electricity from hydro (TWh)  Electricity from nuclear (TWh)  \
0                              0.31                             0.0   
1                              0.50                             0.0   
2                              0.56                             0.0   
...                             ...                             ...   
10646                          4.17                             0.0   
10647                          3.81                             0.0   
10648                          4.00                             0.0   

       Electricity from oil (TWh)  Electricity from gas (TWh)  \
0                            0.16                         0.0   
1                            0.09                         0.0   
2                            0.13                         0.0   
...                           ...                         ...   
10646                        0.04                         0.0   
10647                        0.04                         0.0   
10648                        0.04                         0.0   

       Electricity from coal (TWh)  
0                             0.00  
1                             0.00  
2                             0.00  
...                            ...  
10646                         3.62  
10647                         3.37  
10648                         3.58  

[10649 rows x 12 columns]

### Value counts

In [13]:
df_deg_c = df_deg_c_raw.copy()
df_metrics = df_metrics_raw.copy()
df_hist_ghg = df_hist_ghg_raw.copy()
df_proj_ghg = df_proj_ghg_raw.copy()
df_hist_rf = df_hist_rf_raw.copy()
df_hist_rf_minor = df_hist_rf_minor_raw.copy()
df_emissions = df_emissions_raw.copy()
df_electricity = df_electricity_raw.copy()
df_historical_demand = df_historical_demand_raw.copy()
df_projected_demand = df_projected_demand_raw.copy()

df_deg_c.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 191 entries, 0 to 190
Data columns (total 8 columns):
 #   Column                          Non-Null Count  Dtype  
---  ------                          --------------  -----  
 0   Unnamed: 0                      189 non-null    object 
 1   HadCRUT                         188 non-null    float64
 2   NOAA                            188 non-null    float64
 3   Berkeley                        188 non-null    float64
 4   Kadow                           188 non-null    float64
 5   Unnamed: 5                      0 non-null      float64
 6   HadCRUT confidence limit lower  171 non-null    float64
 7   HadCRUT confidence limit upper  171 non-null    float64
dtypes: float64(7), object(1)
memory usage: 12.1+ KB


In [14]:
df_metrics.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 249 entries, 0 to 248
Data columns (total 18 columns):
 #   Column                              Non-Null Count  Dtype  
---  ------                              --------------  -----  
 0   Name                                248 non-null    object 
 1   CAS                                 249 non-null    object 
 2   Acronym                             163 non-null    object 
 3   Formula                             249 non-null    object 
 4   Lifetime (yr)                       248 non-null    float64
 5   Radiative efficiency (W m-2 ppb-1)  249 non-null    float64
 6   AGWP20 (W m-2 yr kg-1)              249 non-null    float64
 7   GWP20                               249 non-null    float64
 8   AGWP100 (W m-2 yr kg-1)             249 non-null    float64
 9   GWP100                              249 non-null    float64
 10  AGWP500 (W m-2 yr kg-1)             249 non-null    float64
 11  GWP500                              249 non-n

In [15]:
df_hist_ghg.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 172 entries, 0 to 171
Data columns (total 61 columns):
 #   Column                                      Non-Null Count  Dtype  
---  ------                                      --------------  -----  
 0   (# UNITS:, YYYY)                            171 non-null    float64
 1   (ppm, CO2)                                  171 non-null    float64
 2   (ppb, CH4)                                  171 non-null    float64
 3   (ppb, N2O)                                  171 non-null    float64
 4   (ppt, HFC-134a)                             171 non-null    float64
 5   (ppt, HFC-23)                               171 non-null    float64
 6   (ppt, HFC-32)                               171 non-null    float64
 7   (ppt, HFC-125)                              171 non-null    float64
 8   (ppt, HFC-143a)                             171 non-null    float64
 9   (ppt, HFC-152a)                             171 non-null    float64
 10  (ppt, HFC-227e

In [16]:
df_proj_ghg.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 486 entries, 0 to 485
Columns: 139 entries, ('Gas', 'Unit', 'Region', 'Year') to ('Halon 2402', 'ppt', 'Southern Hemisphere', 'Unnamed: 138_level_3')
dtypes: float64(138), int64(1)
memory usage: 527.9 KB


In [17]:
df_hist_rf.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 270 entries, 0 to 269
Data columns (total 20 columns):
 #   Column                          Non-Null Count  Dtype  
---  ------                          --------------  -----  
 0   year                            270 non-null    int64  
 1   co2                             270 non-null    float64
 2   ch4                             270 non-null    float64
 3   n2o                             270 non-null    float64
 4   other_wmghg                     270 non-null    float64
 5   o3                              270 non-null    float64
 6   h2o_stratospheric               270 non-null    float64
 7   contrails                       270 non-null    float64
 8   aerosol-radiation_interactions  270 non-null    float64
 9   aerosol-cloud_interactions      270 non-null    float64
 10  bc_on_snow                      270 non-null    float64
 11  land_use                        270 non-null    float64
 12  volcanic                        270 

In [18]:
df_hist_rf_minor.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 270 entries, 0 to 269
Data columns (total 50 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   year          270 non-null    int64  
 1   HFC-134a      270 non-null    float64
 2   HFC-23        270 non-null    float64
 3   HFC-32        270 non-null    float64
 4   HFC-125       270 non-null    float64
 5   HFC-143a      270 non-null    float64
 6   HFC-152a      270 non-null    float64
 7   HFC-227ea     270 non-null    float64
 8   HFC-236fa     270 non-null    float64
 9   HFC-245fa     270 non-null    float64
 10  HFC-365mfc    270 non-null    float64
 11  HFC-43-10mee  270 non-null    float64
 12  NF3           270 non-null    float64
 13  SF6           270 non-null    float64
 14  SO2F2         270 non-null    float64
 15  CF4           270 non-null    float64
 16  C2F6          270 non-null    float64
 17  C3F8          270 non-null    float64
 18  c-C4F8        270 non-null    

In [19]:
df_emissions.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 36712 entries, 0 to 36711
Columns: 278 entries, source to 2021
dtypes: float64(272), object(6)
memory usage: 77.9+ MB


In [20]:
df_emissions.columns

Index(['source', 'scenario (PRIMAP-hist)', 'area (ISO3)', 'entity', 'unit',
       'category (IPCC2006_PRIMAP)', '1750', '1751', '1752', '1753',
       ...
       '2012', '2013', '2014', '2015', '2016', '2017', '2018', '2019', '2020',
       '2021'],
      dtype='object', length=278)

In [21]:
df_electricity.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10649 entries, 0 to 10648
Data columns (total 12 columns):
 #   Column                                                    Non-Null Count  Dtype  
---  ------                                                    --------------  -----  
 0   Entity                                                    10649 non-null  object 
 1   Code                                                      8347 non-null   object 
 2   Year                                                      10649 non-null  int64  
 3   Other renewables excluding bioenergy (TWh) (zero filled)  10649 non-null  float64
 4   Electricity from bioenergy (TWh) (zero filled)            10649 non-null  float64
 5   Electricity from solar (TWh)                              8683 non-null   float64
 6   Electricity from wind (TWh)                               8676 non-null   float64
 7   Electricity from hydro (TWh)                              8840 non-null   float64
 8   Electricity from

In [22]:
df_historical_demand.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5570 entries, 0 to 5569
Data columns (total 4 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Entity                    5570 non-null   object 
 1   Code                      5106 non-null   object 
 2   Year                      5570 non-null   int64  
 3   Electricity demand (TWh)  5570 non-null   float64
dtypes: float64(1), int64(1), object(2)
memory usage: 174.2+ KB


In [23]:
df_projected_demand.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2930 entries, 0 to 2929
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PUBLICATION  2930 non-null   object 
 1   SCENARIO     2930 non-null   object 
 2   CATEGORY     2930 non-null   object 
 3   PRODUCT      2930 non-null   object 
 4   FLOW         2930 non-null   object 
 5   UNIT         2930 non-null   object 
 6   REGION       2930 non-null   object 
 7   YEAR         2930 non-null   int64  
 8   VALUE        2930 non-null   float64
dtypes: float64(1), int64(1), object(7)
memory usage: 206.1+ KB


### Rename Columns
The columns need more succinct names.

#### Renaming df_deg_c

In [24]:
pd.set_option("display.max_rows", 50)

df_deg_c = df_deg_c_raw.copy()

renaming = {'Unnamed: 0' : 'Year', 'Unnamed: 5' : 
            'Global Annual Average Anomaly (°C)'}
df_deg_c.rename(columns = renaming, inplace = True)

# The two columns on the right need to be dropped, and rows 171–190 need to be
# dropped as they are a new table, not a continuation.

df_deg_c.drop(columns = ['HadCRUT confidence limit lower',
                        'HadCRUT confidence limit upper'],
             index = range(171,191), inplace=True)

df_deg_c['Global Annual Average Anomaly (°C)'] = df_deg_c.iloc[:,1:].mean(axis=1)

df_deg_c.index = df_deg_c['Year']
df_deg_c

Year   HadCRUT      NOAA  Berkeley     Kadow  \
Year                                                 
1850  1850 -0.063333 -0.019804 -0.069216 -0.082353   
1851  1851  0.126667  0.060196  0.000784  0.007647   
1852  1852  0.126667  0.060196  0.040784  0.087647   
1853  1853  0.086667  0.040196  0.030784  0.027647   
1854  1854  0.066667  0.050196  0.020784  0.057647   
...    ...       ...       ...       ...       ...   
2016  2016  1.286667  1.200196  1.320784  1.247647   
2017  2017  1.206667  1.120196  1.230784  1.157647   
2018  2018  1.116667  1.040196  1.150784  1.097647   
2019  2019  1.246667  1.150196  1.290784  1.217647   
2020  2020  1.276667  1.190196  1.310784  1.247647   

      Global Annual Average Anomaly (°C)  
Year                                      
1850                           -0.058676  
1851                            0.048824  
1852                            0.078824  
1853                            0.046324  
1854                            0.048824  
...                                  ...  
2016                            1.263824  
2017                            1.178824  
2018                            1.101324  
2019                            1.226324  
2020                            1.256324  

[171 rows x 6 columns]

#### Renaming df_hist_ghg

In [25]:
df_hist_ghg = df_hist_ghg.iloc[0:171,0:53]

df_hist_ghg.columns = [col[1] + ' (' + col[0] + ')' for col in 
                       df_hist_ghg.columns.values]
renaming = {'YYYY (# UNITS:)': 'Year', 
            'n-C4F10 (Unnamed: 40_level_0)'   : 'n-C4F10 (ppt)',
            'n-C5F12 (Unnamed: 41_level_0)'   : 'n-C5F12 (ppt)',
            'n-C6F14 (Unnamed: 42_level_0)'   : 'n-C6F14 (ppt)',
            'i-C6F14 (Unnamed: 43_level_0)'   : 'i-C6F14 (ppt)',
            'C7F16 (Unnamed: 44_level_0)'     : 'C7F16 (ppt)',
            'C8F18 (Unnamed: 45_level_0)'     : 'C8F18 (ppt)',
            'CFC-112 (Unnamed: 46_level_0)'   : 'CFC-112 (ppt)',
            'CFC-112a (Unnamed: 47_level_0)'  : 'CFC-112a (ppt)',
            'CFC-113a (Unnamed: 48_level_0)'  : 'CFC-113a (ppt)',
            'CFC-114a (Unnamed: 49_level_0)'  : 'CFC-114a (ppt)',
            'HCFC-133a (Unnamed: 50_level_0)' : 'HCFC-133a (ppt)',
            'HCFC-31 (Unnamed: 51_level_0)'   : 'HCFC-31 (ppt)',
            'HCFC-124 (Unnamed: 52_level_0)'  : 'HCFC-124 (ppt)}'}

df_hist_ghg.rename(columns = renaming, inplace = True)
df_hist_ghg['Year'] = df_hist_ghg['Year'].astype(int)
df_hist_ghg.index = df_hist_ghg['Year']

df_hist_ghg

Year  CO2 (ppm)  CH4 (ppb)  N2O (ppb)  HFC-134a (ppt)  HFC-23 (ppt)  \
Year                                                                        
1750  1750      278.3      729.2      270.1            0.00          0.00   
1850  1850      285.5      807.6      272.1            0.00          0.00   
1851  1851      285.6      807.8      272.2            0.00          0.00   
1852  1852      285.8      808.5      272.3            0.00          0.00   
1853  1853      285.9      809.8      272.4            0.00          0.00   
...    ...        ...        ...        ...             ...           ...   
2015  2015      399.4     1834.0      328.3           83.41         28.04   
2016  2016      402.9     1842.2      329.1           89.48         28.95   
2017  2017      405.0     1849.2      330.0           95.75         29.98   
2018  2018      407.4     1857.8      331.2          101.84         31.16   
2019  2019      409.9     1866.3      332.1          107.59         32.41   

      HFC-32 (ppt)  HFC-125 (ppt)  HFC-143a (ppt)  HFC-152a (ppt)  \
Year                                                                
1750          0.00           0.00            0.00            0.00   
1850          0.00           0.00            0.00            0.00   
1851          0.00           0.00            0.00            0.00   
1852          0.00           0.00            0.00            0.00   
1853          0.00           0.00            0.00            0.00   
...            ...            ...             ...             ...   
2015          9.99          18.09           17.57            6.60   
2016         11.97          20.48           19.16            6.66   
2017         14.15          23.25           20.83            6.82   
2018         16.56          26.31           22.42            7.01   
2019         19.98          29.40           24.01            7.13   

      HFC-227ea (ppt)  HFC-236fa (ppt)  HFC-245fa (ppt)  HFC-365mfc (ppt)  \
Year                                                                        
1750             0.00             0.00             0.00              0.00   
1850             0.00             0.00             0.00              0.00   
1851             0.00             0.00             0.00              0.00   
1852             0.00             0.00             0.00              0.00   
1853             0.00             0.00             0.00              0.00   
...               ...              ...              ...               ...   
2015             1.10             0.14             2.23              0.86   
2016             1.21             0.15             2.43              0.93   
2017             1.33             0.17             2.64              0.99   
2018             1.46             0.18             2.85              1.04   
2019             1.59             0.19             3.06              1.09   

      HFC-43-10mee (ppt)  NF3 (ppt)  SF6 (ppt)  SO2F2 (ppt)  CF4 (ppt)  \
Year                                                                     
1750                0.00       0.00       0.00         0.00      34.05   
1850                0.00       0.00       0.00         0.00      34.05   
1851                0.00       0.00       0.00         0.00      34.05   
1852                0.00       0.00       0.00         0.00      34.05   
1853                0.00       0.00       0.00         0.00      34.05   
...                  ...        ...        ...          ...        ...   
2015                0.25       1.30       8.57         2.11      81.92   
2016                0.26       1.45       8.91         2.20      82.74   
2017                0.27       1.63       9.25         2.31      83.65   
2018                0.28       1.83       9.59         2.41      84.58   
2019                0.29       2.05       9.95         2.50      85.48   

      C2F6 (ppt)  C3F8 (ppt)  c-C4F8 (ppt)  CFC-12 (ppt)  CFC-11 (ppt)  \
Year                                                               

#### Renaming df_proj_ghg

In [26]:
# Three columns are needed from this DataFrame, Year, CO2 and NH4 emissions.
# Also, there's no need for data before 2020 because I already have historical
# data for that set.
df_proj_ghg = df_proj_ghg.iloc[5:,[0,1,4]]

# Getting rid of multilevel index names for columns
df_proj_ghg.columns = [col[2] + ' ' + col[0] + ' (' + col[1] + ')' 
                                  for col in df_proj_ghg.columns.values]

# Renaming the first column because it is wrong.
renaming = {'Region Gas (Unit)' : 'Year',
            'World CO2 (ppm)' : 'CO2 (ppm)',
            'World CH4 (ppb)' : 'CH4 (ppb)'}
df_proj_ghg.rename(columns = renaming, inplace = True)
df_proj_ghg.index = df_proj_ghg['Year']

df_proj_ghg

Year   CO2 (ppm)    CH4 (ppb)
Year                               
2020  2020  414.213959  1894.030029
2021  2021  417.013977  1895.909790
2022  2022  419.698975  1895.029541
2023  2023  422.169952  1891.159424
2024  2024  424.442963  1884.499268
...    ...         ...          ...
2496  2496  336.940002   871.387878
2497  2497  336.917999   871.390930
2498  2498  336.895996   871.394897
2499  2499  336.873993   871.398926
2500  2500  336.863007   871.400879

[481 rows x 3 columns]

#### Renaming df_hist_rf

In [27]:
renaming = {'year' : 'Year',
            'co2' : 'CO2 (W/m²)',
            'ch4' : 'CH4 (W/m²)',
            'n2o' : 'N2O (W/m²)',
            'other_wmghg' : 'Minor GHG (W/m²)',
            'o3' : 'O3 (W/m²)',
            'h2o_stratospheric' : 'Stratospheric H2O (W/m²)',
            'contrails' : 'Contrails (W/m²)',
            'aerosol-radiation_interactions' : 'Aerosol Radiation (W/m²)',
            'aerosol-cloud_interactions' : 'Aerosol Cloud (W/m²)',
            'bc_on_snow' : 'Snow (W/m²)',
            'land_use' : 'Land Use (W/m²)',
            'volcanic' : 'Volcanic (W/m²)',
            'solar' : 'Solar (W/m²)',
            'nonco2_wmghg' : 'NonCO2 GHG (W/m²)',
            'aerosol' : 'Aerosol (W/m²)',
            'chapter2_other_anthro' : 'Ch2 Other Anthro (W/m²)',
            'total_anthropogenic' : 'Total Antropgenic (W/m²)',
            'total_natural' : 'Total Natural (W/m²)',
            'total' : 'Total (W/m²)'}

df_hist_rf.rename(columns = renaming, inplace = True)
df_hist_rf.index = df_hist_rf['Year']
df_hist_rf

Year  CO2 (W/m²)  CH4 (W/m²)  N2O (W/m²)  Minor GHG (W/m²)  O3 (W/m²)  \
Year                                                                          
1750  1750    0.000000    0.000000    0.000000      0.000000e+00   0.000000   
1751  1751    0.001416    0.000508    0.000074      7.958010e-10   0.000300   
1752  1752    0.002832    0.001016    0.000148      1.591602e-09   0.000600   
1753  1753    0.004247    0.001524    0.000222      2.387403e-09   0.000900   
1754  1754    0.005662    0.002031    0.000296      3.183204e-09   0.001200   
...    ...         ...         ...         ...               ...        ...   
2015  2015    2.010013    0.531999    0.196590      4.008651e-01   0.467400   
2016  2016    2.058493    0.535044    0.199149      4.026474e-01   0.463533   
2017  2017    2.088686    0.537665    0.202033      4.046273e-01   0.459667   
2018  2018    2.122080    0.540821    0.205654      4.066049e-01   0.467067   
2019  2019    2.156278    0.543983    0.208463      4.080644e-01   0.474467   

      Stratospheric H2O (W/m²)  Contrails (W/m²)  Aerosol Radiation (W/m²)  \
Year                                                                         
1750                  0.000000          0.000000                  0.000000   
1751                  0.000047          0.000000                  0.000601   
1752                  0.000093          0.000000                  0.001247   
1753                  0.000140          0.000000                  0.000537   
1754                  0.000187          0.000000                 -0.000875   
...                        ...               ...                       ...   
2015                  0.048899          0.050999                 -0.228510   
2016                  0.049178          0.053424                 -0.219798   
2017                  0.049419          0.056725                 -0.211978   
2018                  0.049709          0.057400                 -0.215540   
2019                  0.050000          0.057535                 -0.215562   

      Aerosol Cloud (W/m²)  Snow (W/m²)  Land Use (W/m²)  Volcanic (W/m²)  \
Year                                                                        
1750              0.000000     0.000000         0.000000         0.199978   
1751              0.004674     0.000017        -0.000229         0.199990   
1752              0.007281     0.000035        -0.000458         0.199995   
1753              0.004742     0.000052        -0.000687         0.199996   
1754             -0.002000     0.000070        -0.000916         0.199996   
...                    ...          ...              ...              ...   
2015             -0.888940     0.082637        -0.198663         0.109650   
2016             -0.867454     0.081655        -0.198998         0.127189   
2017             -0.850840     0.081292        -0.199332         0.150614   
2018             -0.849968     0.080728        -0.199666         0.139917   
2019             -0.842778     0.080000        -0.200000         0.139917   

      Solar (W/m²)  NonCO2 GHG (W/m²)  Aerosol (W/m²)  \
Year                                                    
1750      0.097590           0.000000        0.000000   
1751      0.079244           0.000582        0.005274   
1752      0.049166           0.001164        0.008528   
1753      0.012988           0.001746        0.005278   
1754     -0.021427           0.002327       -0.002874   
...            ...                ...             ...   
2015      0.029197           1.129454       -1.117450   
2016     -0.007587           1.136841       -1.087251   
2017     -0.017467           1.144326       -1.062817   
2018     -0.021468           1.153080       -1.065508   
2019     -0.022173           1.160510       -1.058340   

      Ch2 Other Anthro (W/m²)  Total Antropgenic (W/m²)  Total Natural (W/m²)  \
Year                                                                            
1750                 0.000000                  0.000000  

#### Renaming df_emissions

In [28]:
# I only want emissions data from the "Fuel Combustion" section of the National.
# Greenhouse Inventory
df_emissions = df_emissions.loc[
    df_emissions['category (IPCC2006_PRIMAP)'] == '1.A'].iloc[:,:]

# HISTCR: In this scenario country-reported data (CRF, BUR, UNFCCCDI) 
# HISTTP: In this scenario third-party data (CDIAC, FAO, Andrew, EDGAR, BP) 
# I'll use third-party data
df_emissions = df_emissions.loc[df_emissions[
    'scenario (PRIMAP-hist)'] == 'HISTTP']

# I'm only concerned with CH4 and CO2
df_emissions = df_emissions.loc[
    (df_emissions['entity'] == 'CH4') | 
    (df_emissions['entity'] == 'CO2')].iloc[:,:]

# I'll create a list of the columns for the transposed DataFrame

col_idx = []
country_df_emissions = []

for i in df_emissions.index:
    country = df_emissions.loc[i,'area (ISO3)']
    
    # I'll create a list of the countries included in the emissions data.
    if country not in country_df_emissions:
        country_df_emissions.append(country)
        
    gas = df_emissions.loc[i,'entity']
    new_index = country + ' - ' + gas + ' (Gg/yr)'
    col_idx.append(new_index)
    
# I don't need the early columns anymore.
df_emissions = df_emissions.iloc[:,6:]

df_emissions = df_emissions.transpose()
df_emissions.columns = col_idx
df_emissions = df_emissions
df_emissions.reset_index(inplace=True)
df_emissions.rename(columns = {'index' : 'Year'}, inplace=True)
df_emissions.index = df_emissions['Year']
df_emissions

Year  ABW - CH4 (Gg/yr)  ABW - CO2 (Gg/yr)  AFG - CH4 (Gg/yr)  \
Year                                                                  
1750  1750           0.005636            0.00000           1.927227   
1751  1751           0.005672            0.00000           1.935082   
1752  1752           0.005708            0.00000           1.942935   
1753  1753           0.005744            0.00000           1.950788   
1754  1754           0.005780            0.00000           1.958638   
...    ...                ...                ...                ...   
2017  2017           0.125945          916.67500           6.486574   
2018  2018           0.131889          944.26293           6.564918   
2019  2019           0.131870          975.66779           6.516839   
2020  2020           0.120299          858.81460           6.651218   
2021  2021           0.130702          962.39767           6.674809   

      AFG - CO2 (Gg/yr)  AGO - CH4 (Gg/yr)  AGO - CO2 (Gg/yr)  \
Year                                                            
1750             0.0000           1.869069              0.000   
1751             0.0000           1.869472              0.000   
1752             0.0000           1.869876              0.000   
1753             0.0000           1.870280              0.000   
1754             0.0000           1.870683              0.000   
...                 ...                ...                ...   
2017          6820.0620          56.946942          21714.197   
2018          7214.4880          57.685349          19906.422   
2019          7885.6184          58.624918          20102.879   
2020          7818.3493          59.707141          18941.399   
2021          7907.2685          59.853257          20654.419   

      AIA - CH4 (Gg/yr)  AIA - CO2 (Gg/yr)  ALB - CH4 (Gg/yr)  \
Year                                                            
1750           0.000012                NaN           5.652923   
1751           0.000012                NaN           5.670996   
1752           0.000013                NaN           5.689070   
1753           0.000013                NaN           5.707144   
1754           0.000013                NaN           5.725217   
...                 ...                ...                ...   
2017           0.004789          143.00130           2.271355   
2018           0.004586          147.30502           2.253825   
2019           0.004478          152.20417           2.199630   
2020           0.003697          133.97508           2.147353   
2021           0.004120          150.13404           2.129105   

      ALB - CO2 (Gg/yr)  AND - CH4 (Gg/yr)  AND - CO2 (Gg/yr)  \
Year                                                            
1750             0.0000           0.203505                NaN   
1751             0.0000           0.203711                NaN   
1752             0.0000           0.203914                NaN   
1753             0.0000           0.204111                NaN   
1754             0.0000           0.204304                NaN   
...                 ...                ...                ...   
2017          4627.3754           0.133442          465.67090   
2018          4183.7455           0.129265          448.26156   
2019          4181.7755           0.130587          438.12441   
2020          4053.2563           0.124819          376.25670   
2021          3152.3792           0.130387          423.02208   

      ANNEXI - CH4 (Gg/yr)  ANNEXI - CO2 (Gg/yr)  ANT - CH4 (Gg/yr)  \
Year                                                                  
1750             2822.0550          1.131973e-01           0.042800   
1751             2830.9904          9.357534e+03           0.043098   
1752             2839.8879          9.361203e+03           0.043396   
1753             2848.7387          9.361205e+03           0.043693   
1754             2857.5517          9.364874e+03           0.043989   
...                    ...                   ..

#### Renaming df_electricity

In [29]:
# I want to create a dictionary to reference the country codes used in the 
# electricity production data.

country_code_elec = {}
country_nan_elec = []

for i in range(len(df_electricity)):
    if (type(df_electricity.loc[i, 'Code']) != str):
        if df_electricity.loc[i, 'Entity'] not in country_nan_elec:
            country_nan_elec.append(df_electricity.loc[i, 'Entity'])
    else:
        if df_electricity.loc[i, 'Code'] not in country_code_elec:
            country_code_elec[df_electricity.loc[
                i, 'Code']] = df_electricity.loc[i, 'Entity']

In [30]:
# I'll create a dataframe to place rearranged electricity data into.
print('The electricity generation data includes the years',
      df_electricity['Year'].min(), '–', str(df_electricity['Year'].max())+'.')
df_elec = pd.DataFrame(data = range(df_electricity['Year'].min(),
                                    df_electricity['Year'].max()+1),
                                    columns = ['Year'])

The electricity generation data includes the years 1861 – 2022.


In [31]:
# Renaming the columns of the electricity genation DataFrame
renaming = {'Entity' : 'Country',
            'Other renewables excluding bioenergy (TWh) (zero filled)' : 
            'Other Renewables (TWh)',
            'Electricity from bioenergy (TWh) (zero filled)' : 
            'Bioenergy (TWh)',
            'Electricity from solar (TWh)' : 'Solar (TWh)',
            'Electricity from wind (TWh)' : 'Wind (TWh)',
            'Electricity from hydro (TWh)' : 'Hydro (TWh)',
            'Electricity from nuclear (TWh)':'Nuclear (TWh)',
            'Electricity from oil (TWh)' : 'Oil (TWh)',
            'Electricity from gas (TWh)' : 'Gas (TWh)',
            'Electricity from coal (TWh)' : 'Coal (TWh)'}

df_electricity.rename(columns = renaming, inplace = True)

In [32]:
df_elec = df_elec.copy()
df_elec.index = df_elec['Year']
df_elec

# I don't want to use anything from the electricity generation DataFrame that
# isn't found in the emissions DataFrame.
for code in country_df_emissions:
    temp = df_electricity.loc[df_electricity['Code'] == code]
    temp.columns = [code + ' | ' + col for col in temp.columns.values]
    temp = temp.iloc[:,2:]
    temp.rename(columns = {temp.columns[0] : 'Year'}, inplace = True)
    temp.index = temp['Year']
    temp = temp.iloc[:,1:]
    for col in temp.columns:
        if temp[col].sum() == 0:
            temp.drop(columns = col, inplace = True)
    df_elec = pd.concat([df_elec, temp], axis=1)

In [33]:
df_elec

Year  ABW | Solar (TWh)  ABW | Wind (TWh)  ABW | Oil (TWh)  \
Year                                                               
1861  1861                NaN               NaN              NaN   
1862  1862                NaN               NaN              NaN   
1863  1863                NaN               NaN              NaN   
1864  1864                NaN               NaN              NaN   
1865  1865                NaN               NaN              NaN   
...    ...                ...               ...              ...   
2018  2018               0.01              0.14             0.76   
2019  2019               0.01              0.14             0.77   
2020  2020               0.01              0.14             0.73   
2021  2021               0.01              0.14             0.78   
2022  2022                NaN               NaN              NaN   

      AFG | Solar (TWh)  AFG | Hydro (TWh)  AFG | Oil (TWh)  \
Year                                                          
1861                NaN                NaN              NaN   
1862                NaN                NaN              NaN   
1863                NaN                NaN              NaN   
1864                NaN                NaN              NaN   
1865                NaN                NaN              NaN   
...                 ...                ...              ...   
2018               0.04               0.93             0.20   
2019               0.05               0.84             0.18   
2020               0.06               0.62             0.12   
2021               0.08               0.62             0.13   
2022                NaN                NaN              NaN   

      AGO | Bioenergy (TWh)  AGO | Solar (TWh)  AGO | Hydro (TWh)  \
Year                                                                
1861                    NaN                NaN                NaN   
1862                    NaN                NaN                NaN   
1863                    NaN                NaN                NaN   
1864                    NaN                NaN                NaN   
1865                    NaN                NaN                NaN   
...                     ...                ...                ...   
2018                   0.17               0.02               9.79   
2019                   0.25               0.02              10.87   
2020                   0.26               0.02              11.95   
2021                   0.28               0.02              11.50   
2022                    NaN                NaN                NaN   

      AGO | Oil (TWh)  AGO | Gas (TWh)  ALB | Solar (TWh)  ALB | Hydro (TWh)  \
Year                                                                           
1861              NaN              NaN                NaN                NaN   
1862              NaN              NaN                NaN                NaN   
1863              NaN              NaN                NaN                NaN   
1864              NaN              NaN                NaN                NaN   
1865              NaN              NaN                NaN                NaN   
...               ...              ...                ...                ...   
2018             0.46             2.40               0.00               8.55   
2019             0.68             3.58               0.02               5.18   
2020             0.70             3.67               0.03               5.28   
2021             0.74             3.89                NaN                NaN   
2022              NaN              NaN                NaN                NaN   

      ALB | Oil (TWh)  ARE | Bioenergy (TWh)  ARE | Solar (TWh)  \
Year                                                              
1861              NaN                    NaN                NaN   
1862              NaN                    NaN                NaN   
1863              NaN                    NaN                NaN   
1864              NaN      

#### Renaming df_projected_demand

In [208]:
# Renaming Columns
df_projected_demand = df_projected_demand_raw.copy()
renaming = {'PUBLICATION' : 'Publication',
            'SCENARIO' : 'Scenario',
            'CATEGORY' : 'Category',
            'PRODUCT' : 'Product',
            'FLOW' : 'Flow',
            'UNIT' : 'Unit',
            'REGION' : 'Region',
            'YEAR' : 'Year',
            'VALUE' : 'Value'}
df_projected_demand.rename(columns = renaming, inplace = True)

In [209]:
# I don't know what the carbon data is in this 
df_projected_demand = df_projected_demand.loc[
    df_projected_demand['Category'] == 'Energy']

# Each cell of Publication, and now Category, has the same value, I'll delete
# both columns.
df_projected_demand.drop(columns = ['Publication', 'Category'], inplace = True)

# I'm intrigued by the data in the Scenario column. There are three categories:
df_projected_demand['Scenario'].value_counts()

Stated Policies Scenario               1796
Announced Pledges Scenario              768
Net Zero Emissions by 2050 Scenario      30
Name: Scenario, dtype: int64

In [210]:
# The Announced Pledges Scenario could hold some interesting data, as well as
# the Net Zero Emissions by 2050 Scenario. Putting this data into the same
# Dataframe as the information I need will not be possible, so I'll split it
# into three different scenarios. 

df_proj_stat = df_projected_demand.loc[
    df_projected_demand['Scenario'] == 'Stated Policies Scenario'].copy()
df_proj_stat.drop(columns = ['Scenario'], inplace = True)

df_proj_ann = df_projected_demand.loc[
    df_projected_demand['Scenario'] == 'Announced Pledges Scenario'].copy()
df_proj_ann.drop(columns = ['Scenario'], inplace = True)

df_proj_zero = df_projected_demand.loc[
    df_projected_demand[
        'Scenario'] == 'Net Zero Emissions by 2050 Scenario'].copy()
df_proj_zero.drop(columns = ['Scenario'], inplace = True)

In [211]:
# Now I want to see what the Product column does.
df_proj_ann['Product'].value_counts()

Total                          252
Natural gas                     86
Coal                            84
Hydrogen                        64
Renewables                      64
Oil                             62
Solar PV                        32
Nuclear                         32
Wind                            32
Other                            4
LPG and ethane                   2
Diesel                           2
CTL, GTL and additives           2
Other products                   2
Extra-heavy oil and bitumen      2
Gasoline                         2
Naphtha                          2
Natural gas liquids              2
Tight oil                        2
Coalbed methane                  2
Shale gas                        2
Tight gas                        2
Biofuels                         2
Conventional crude oil           2
Total liquids                    2
Refinery products                2
Direct use of crude oil          2
Refinery market share            2
Total oil           

I already have a reliable source for a breakdown of different region's energy production. I was primarily interested in this DataFrame because it shows what the increase in demand will be. The future of energy product is the variable I will adjust in this project. Therefore, I think I only need the information in the Total Energy needs. I'll drop the rest. The net zero pledges don't have a total energy category, so I won't need to drop anything there.

In [212]:
df_proj_stat = df_proj_stat.loc[df_proj_stat['Product'] == 'Total']
df_proj_stat.drop(columns = 'Product', inplace = True)

df_proj_ann = df_proj_ann.loc[df_proj_ann['Product'] == 'Total']
df_proj_ann.drop(columns = 'Product', inplace = True)

# Now I'll check the "Flow" column
df_proj_stat['Flow'].value_counts()

Industry                   80
Total energy supply        80
Electricity generation     80
Buildings                  80
Total final consumption    80
Transport                  80
Refinery runs              45
Refining capacity          45
Name: Flow, dtype: int64

Again, I really only wanted the Total energy supply information from this DataFrame. I looked up each definition of these terms in the report, and learned that only one of them is relevant to this project, defined below.

[Industry](https://iea.blob.core.windows.net/assets/830fe099-5530-48f2-a7c1-11f35d510983/WorldEnergyOutlook2022.pdf#page=499): The sector includes fuel used within the manufacturing and construction industries. Key industry branches include iron and steel, chemical and petrochemical, cement, aluminium, and pulp and paper. Use by industries for the transformation of energy into another form or for the production of fuels is excluded and reported separately under other energy sector. There is an exception for fuel transformation in blast furnaces and coke ovens, which are reported within iron and steel. Consumption of fuels for the transport of goods is reported as part of the transport sector, while consumption by off‐road vehicles is reported under industry.

[Total energy supply (TES)](https://iea.blob.core.windows.net/assets/830fe099-5530-48f2-a7c1-11f35d510983/WorldEnergyOutlook2022.pdf#page=497): Represents domestic demand only and is broken down into electricity and heat generation, other energy sector and total final consumption.

[Electricity generation](https://iea.blob.core.windows.net/assets/830fe099-5530-48f2-a7c1-11f35d510983/WorldEnergyOutlook2022.pdf#page=490): Defined as the total amount of electricity generated by power only or combined heat and power plants including generation required for own use. This is also referred to as gross generation.

[Buildings](https://iea.blob.core.windows.net/assets/830fe099-5530-48f2-a7c1-11f35d510983/WorldEnergyOutlook2022.pdf#page=488): The buildings sector includes energy used in residential and services buildings. Services buildings include commercial and institutional buildings and other non‐specified buildings. Building energy use includes space heating and cooling, water heating, lighting, appliances and cooking equipment.

[Total final consumption (TFC)](https://iea.blob.core.windows.net/assets/830fe099-5530-48f2-a7c1-11f35d510983/WorldEnergyOutlook2022.pdf#page=497): Is the sum of consumption by the various end‐use sectors. TFC is broken down into energy demand in the following sectors: industry (including manufacturing, mining, chemicals production, blast furnaces and coke ovens), transport, buildings (including residential and services) and other (including agriculture and other non‐energy use). It excludes international marine and aviation bunkers, except at world level where it is included in the transport sector.

[Transport](https://iea.blob.core.windows.net/assets/830fe099-5530-48f2-a7c1-11f35d510983/WorldEnergyOutlook2022.pdf#page=498): Fuels and electricity used in the transport of goods or people within the national territory irrespective of the economic sector within which the activity occurs. This includes fuel and electricity delivered to vehicles using public roads or for use in rail vehicles; fuel delivered to vessels for domestic navigation; fuel delivered to aircraft for domestic aviation; and energy consumed in the delivery of fuels through pipelines. Fuel delivered to international marine and aviation bunkers is presented only at the world level and is excluded from the transport sector at a domestic level. 

In [213]:
# I want to see what these numbers say for the "World" region.
df_proj_stat.loc[(df_proj_stat['Region'] == 'World') & 
                 (df_proj_stat['Year'] == 2021)]

Flow                     Unit Region  Year      Value
2         Total energy supply                       PJ  World  2021    624.164
698         Refining capacity  Million barrels per day  World  2021    101.200
703             Refinery runs  Million barrels per day  World  2021     77.900
1157   Electricity generation                      TWh  World  2021  28333.900
1941  Total final consumption                       PJ  World  2021    439.103
2053                 Industry                       PJ  World  2021    166.738
2165                Transport                       PJ  World  2021    113.433
2277                Buildings                       PJ  World  2021    132.436

Wow. These conversions don't make a lick of sense.

$ 28333.9 \ TWh \times \frac{3.6 PJ}{TwH} = 102002.04 \ PJ$

If these numbers are accurate, that means that in 2021, the world generated more electricity than the total final consumption. Since electricity generation is one of the sectors added to Total Final consumption, that doesn't make a lot of sense.

I opened the report to see if I could confirm what was going on. Fortunately, I was able confirm that this was a mere typo. [Table 5.1 on Page 239](https://iea.blob.core.windows.net/assets/830fe099-5530-48f2-a7c1-11f35d510983/WorldEnergyOutlook2022.pdf#page=239) of the report shared these same numbers, but confirmed they are not in petajoules, but in exajoules, which equal a thousand petajoules. 

$ 28333.9 \ TWh \times \frac{.0036 EJ}{TwH} = 102 \ EJ$

I'll change the units on this.

In [214]:
for i in df_proj_stat.index:
    if df_proj_stat.loc[i,'Unit'] == 'PJ':
        df_proj_stat.loc[i,'Unit'] = 'EJ'
        
for i in df_proj_ann.index:
    if df_proj_ann.loc[i,'Unit'] == 'PJ':
        df_proj_ann.loc[i,'Unit'] = 'EJ'

for i in df_proj_zero.index:
    if df_proj_zero.loc[i,'Unit'] == 'PJ':
        df_proj_zero.loc[i,'Unit'] = 'EJ'
        
df_proj_stat.loc[(df_proj_stat['Region'] == 'World') & 
                 (df_proj_stat['Year'] == 2021)]

Flow                     Unit Region  Year      Value
2         Total energy supply                       EJ  World  2021    624.164
698         Refining capacity  Million barrels per day  World  2021    101.200
703             Refinery runs  Million barrels per day  World  2021     77.900
1157   Electricity generation                      TWh  World  2021  28333.900
1941  Total final consumption                       EJ  World  2021    439.103
2053                 Industry                       EJ  World  2021    166.738
2165                Transport                       EJ  World  2021    113.433
2277                Buildings                       EJ  World  2021    132.436

I'm still not sure which of these values are relevant for this analysis. I'll compare the above numbers to the electricity generation database from BP and see how they compare. Fortunatley, the BP database has a value for the whole world in 2021, split across different electricity genertaion methods. If I add them up, I'll have a number to compare.

In [215]:
electricity_2021 = df_electricity.loc[(df_electricity['Country'] == 'World') &
                   (df_electricity['Year'] == 2021)].copy()
Twh = electricity_2021.iloc[:,3:].values
BP_2021 = np.sum(Twh)
BP_2021

27812.739999999998

In [216]:
28333.900 / BP_2021

1.018738175382936

I'd say a 2% difference means I'm on the right track. I'll use the electricity generation values from the IEA database.

In [217]:
df_proj_stat = df_proj_stat.loc[
    df_proj_stat['Flow'] == 'Electricity generation']
df_proj_stat.drop(columns = 'Flow', inplace = True)

df_proj_ann = df_proj_ann.loc[
    df_proj_ann['Flow'] == 'Electricity generation']
df_proj_ann.drop(columns = 'Flow', inplace = True)

In [220]:
# START HERE START HERE

Unit                     Region  Year     Value
1160  TWh                      World  2030  35878.20
1161  TWh                      World  2050  61268.40
1167  TWh              North America  2030   6043.34
1168  TWh              North America  2050   9749.09
1174  TWh              United States  2030   4869.08
1175  TWh              United States  2050   7936.87
1181  TWh  Central and South America  2030   1789.15
1182  TWh  Central and South America  2050   3542.67
1188  TWh                     Brazil  2030    810.95
1189  TWh                     Brazil  2050   1386.84
1195  TWh                     Europe  2030   5165.00
1196  TWh                     Europe  2050   7538.53
1202  TWh             European Union  2030   3582.69
1203  TWh             European Union  2050   5017.28
1209  TWh                     Africa  2030   1329.73
1210  TWh                     Africa  2050   3703.51
1216  TWh                Middle East  2030   1606.01
1217  TWh                Middle East  2050   3459.94
1223  TWh                    Eurasia  2030   1524.98
1224  TWh                    Eurasia  2050   1925.10
1230  TWh                     Russia  2030   1149.31
1231  TWh                     Russia  2050   1296.45
1237  TWh               Asia Pacific  2030  18420.00
1238  TWh               Asia Pacific  2050  31349.60
1244  TWh                      China  2030  10958.30
1245  TWh                      China  2050  16109.20
1251  TWh                      India  2030   2688.82
1252  TWh                      India  2050   6552.76
1258  TWh                      Japan  2030   1035.70
1259  TWh                      Japan  2050   1302.69
1265  TWh             Southeast Asia  2030   1751.39
1266  TWh             Southeast Asia  2050   3561.04

In [37]:
df_metrics
df_hist_ghg
df_proj_ghg
df_hist_rf
df_hist_rf_minor
df_emissions
df_electricity
df_historical_demand
df_projected_demand

Year                    Scenario                    Category Product  \
0     2010    Stated Policies Scenario                      Energy   Total   
1     2020    Stated Policies Scenario                      Energy   Total   
2     2021    Stated Policies Scenario                      Energy   Total   
3     2030    Stated Policies Scenario                      Energy   Total   
4     2050    Stated Policies Scenario                      Energy   Total   
...    ...                         ...                         ...     ...   
2925  2021    Stated Policies Scenario  CO2 combustion and process   Total   
2926  2030    Stated Policies Scenario  CO2 combustion and process   Total   
2927  2050    Stated Policies Scenario  CO2 combustion and process   Total   
2928  2030  Announced Pledges Scenario  CO2 combustion and process   Total   
2929  2050  Announced Pledges Scenario  CO2 combustion and process   Total   

                         Flow          Region    Unit     Value  
0         Total energy supply           World      PJ   541.981  
1         Total energy supply           World      PJ   592.311  
2         Total energy supply           World      PJ   624.164  
3         Total energy supply           World      PJ   673.271  
4         Total energy supply           World      PJ   740.009  
...                       ...             ...     ...       ...  
2925  Total final consumption  Southeast Asia  Mt CO2   933.700  
2926  Total final consumption  Southeast Asia  Mt CO2  1230.620  
2927  Total final consumption  Southeast Asia  Mt CO2  1422.280  
2928  Total final consumption  Southeast Asia  Mt CO2  1081.410  
2929  Total final consumption  Southeast Asia  Mt CO2   670.950  

[2930 rows x 8 columns]

In [38]:
jnk = df_elec.transpose()
jnk.isna().sum()

Year
1861    953
1862    953
1863    953
1864    953
1865    953
       ... 
2018      0
2019      0
2020      0
2021      4
2022    749
Length: 162, dtype: int64

In [39]:
# A look at the regions included in this Dataset

df_projected_demand['Region'].value_counts()

World                        502
Middle East                  170
North America                170
Southeast Asia               170
Asia Pacific                 170
Africa                       170
Europe                       170
European Union               160
Eurasia                      160
Central and South America    160
Brazil                       149
China                        149
India                        149
Russia                       149
United States                139
Japan                        139
Atlantic Basin                10
East of Suez                  10
Japan and Korea               10
Other                         10
OPEC                           7
Non-OPEC                       7
Name: Region, dtype: int64

Unfortunately, the full dataset with individual country data is behind a paywall. The IEA's **World Energy Outlook 2022** Report splits the world into seven regions on [Page 499](https://iea.blob.core.windows.net/assets/830fe099-5530-48f2-a7c1-11f35d510983/WorldEnergyOutlook2022.pdf#page=499):

* North America
* Central & South America
* Europe
* Africa
* Middle East
* Eurasia
* Asia Pacific

Below I'll create lists to group the countries together, along with other groups the report defines.

**North America**

In [40]:
n_america = ['CAN', 'MEX', 'USA']

**Central & South America**

In [41]:
cen_s_america = ['ATG', 'ARG', 'ABW', 'BHS', 'BRB', 'BLZ', 'BMU', 'VEN', 'BRA',
                 'VGB', 'CYM', 'CHL', 'COL', 'CRI', 'CUB', 'CUW', 'DMA', 'DOM',
                 'ECU', 'SLV', 'FLK', 'GUF', 'GRD', 'GLP', 'GTM', 'GUY', 'HTI',
                 'HND', 'JAM', 'MTQ', 'MSR', 'NIC', 'PAN', 'PRY', 'PER', 'BOL',
                 'KNA', 'LCA', 'SPM', 'SUR', 'TTO', 'TCA', 'URY']

**Europe**

In [42]:
european_u = ['AUT', 'BEL', 'BGR', 'HRV', 'CYP', 'CZE', 'DNK', 'EST', 'FIN',
              'FRA', 'DEU', 'GRC', 'HUN', 'IRL', 'ITA', 'LVA', 'LTU', 'LUX',
              'MLT', 'NLD', 'POL', 'PRT', 'ROU', 'SVK', 'SVN', 'ESP', 'SWE']

In [43]:
europe = european_u + ['ALB', 'BLR', 'BIH', 'GIB', 'ISL', 'ISR', 'OWID_KOS',
                       'MNE', 'MKD', 'NOR', 'MDA', 'SRB', 'CHE', 'TUR', 'UKR',
                       'GBR']

**Africa**

In [44]:
n_africa = ['DZA', 'EGY', 'LBY', 'MAR', 'TUN']

In [45]:
sub_africa = ['AGO', 'BEN', 'BWA', 'BFA', 'BDI', 'CPV', 'CMR', 'CAF', 'TCD',
              'COM', 'CIV', 'COD', 'DJI', 'GNQ', 'ERI', 'ETH', 'GAB', 'GMB',
              'GHA', 'GIN', 'GNB', 'KEN', 'SWZ', 'LSO', 'LBR', 'MDG', 'MWI',
              'MLI', 'MRT', 'MUS', 'MOZ', 'NAM', 'NER', 'NGA', 'COG', 'REU',
              'RWA', 'STP', 'SEN', 'SYC', 'SLE', 'SOM', 'ZAF', 'SSD', 'SDN',
              'TGO', 'UGA', 'TZA', 'ZMB', 'ZWE']

In [46]:
africa = n_africa + sub_africa

**Middle East**

In [47]:
mid_east = ['BHR', 'IRQ', 'IRN', 'JOR', 'KWT', 'LBN', 'OMN', 'QAT', 'SAU',
            'SYR', 'ARE', 'YEM']

**Eurasia**

In [48]:
caspian = ['ARM', 'AZE', 'GEO', 'KAZ', 'KGZ', 'TJK', 'TKM', 'UZB']

In [49]:
eurasia = caspian + ['RUS']

**Asia Pacific**

In [50]:
se_asia = ['BRN', 'KHM', 'IDN', 'LAO', 'MYS', 'MMR', 'PHL', 'SGP', 'THA','VNM']

In [51]:
asia_pacific = se_asia + ['AFG', 'AUS', 'BGD', 'BTN', 'TWN', 'COK', 'PRK',
                          'FJI', 'PYF', 'IND', 'JPN', 'KIR', 'KOR', 'MAC',
                          'MDV', 'MNG', 'NPL', 'NCL', 'NZL', 'PAK', 'PNG',
                          'CHN', 'WSM', 'SLB', 'LKA', 'TLS', 'VUT']

# China: Includes the (People's Republic of) China and Hong Kong, China.
# I'll create a separate DF for linking with other data.
asia_pacific_hkg = asia_pacific + ['HKG']

**Other Divisions**

In [52]:
iea_countries = ['AUS', 'AUT', 'BEL', 'CAN', 'CZE', 'DNK', 'EST', 'FIN', 'FRA',
                 'DEU', 'GRC', 'HUN', 'IRL', 'ITA', 'JPN', 'KOR', 'LTU', 'LUX',
                 'MEX', 'NLD', 'NZL', 'NOR', 'POL', 'PRT', 'SVK', 'ESP', 'SWE',
                 'CHE', 'TUR', 'GBR', 'USA']

In [53]:
oecd = ['AUS', 'AUT', 'BEL', 'CAN', 'CHL', 'COL', 'CRI', 'CZE', 'DNK', 'EST',
        'FIN', 'FRA', 'DEU', 'GRC', 'HUN', 'ISL', 'IRL', 'ISR', 'ITA', 'JPN',
        'KOR', 'LVA', 'LTU', 'LUX', 'MEX', 'NLD', 'NZL', 'NOR', 'POL', 'PRT',
        'SVK', 'SVN', 'ESP', 'SWE', 'CHE', 'TUR', 'GBR', 'USA']

In [54]:
opec = ['DZA', 'AGO', 'COG', 'GNQ', 'GAB', 'IRN', 'IRQ', 'KWT', 'LBY', 'NGA',
        'SAU', 'ARE', 'VEN']

In [55]:
adv_eco = oecd + ['BGR', 'HRV', 'CYP', 'MLT', 'ROU']

In [56]:
world = (n_america + cen_s_america + europe + africa + mid_east + eurasia + 
         asia_pacific)

world_hkg = world + ['HKG']

In [57]:
dev_asia = asia_pacific
dev_asia.remove('AUS')
dev_asia.remove('JPN')
dev_asia.remove('KOR')
dev_asia.remove('NZL')

dev_asia_hkg = dev_asia + ['HKG']

In [58]:
# emg_dev = All other countries not included in the advanced economies regional
# grouping.
emg_dev = world.copy()
for con in adv_eco:
    emg_dev.remove(con)
    
emg_dev_hkg = emg_dev + ['HKG']

In [59]:
l_america = cen_s_america + ['MEX']

In [60]:
# Non‐OECD: All other countries not included in the OECD regional grouping.

non_oecd = world.copy()
for con in oecd:
    non_oecd.remove(con)

non_oecd_hkg = non_oecd + ['HKG']

In [61]:
# Non‐OPEC: All other countries not included in the OPEC regional grouping.

non_opec = world.copy()
for con in opec:
    non_opec.remove(con)
    
non_opec_hkg = non_opec + ['HKG']

Countries that are left out:
Because I don't have corresponding information in other datasets, I had to leave out Palau (PW), Bonaire BQ-BO, Saba, Sint Eustatius (BQ-SE),  Sint Maarten (SX), Saint Vincent and the Grenadines (VC), & Anguilla (AI)  from this dataset. Saint P has a population of about 100,000, and the other  islands combined represent less than 65,000 people.

### Visualize the quantities of the data.

## Preparing Data For Analysis

### Testing for bad data

## Frequency Distributions

# Building Models
It's finally time to build the classification models. I will fit each vectorization technique with the following models:
1. Multinomial Naive Bayes 
2. Logistic Regression
3. Support Vector Machine
4. RandomForest
5. XGBoost

I'll explain each of the models below in the same section in which they are created. Before I start, here's one last preview of the DataFrame I am about to model.

## Final Model Selection

# Tuning Models

# Final Model And Analysis

# Conclusion

## Limitations of Scope / Provided Data

## Future Research Opportunities

## Recommendations

That's a wrap! Thanks for hiring Greg Osborne and I hope to work with you more in the future.

## Grading

***To pass this project, you must pass each rubric objective.*** The project rubric objectives for Capstone are:

1. Attention to Detail
2. Project Motivation
3. Independent Learning
4. Reproducibility

### Attention to Detail

Once again, the Attention to Detail standard has increased. ***In Capstone, you need to complete 100% (10 out of 10) or more of the checklist elements in order to pass the Attention to Detail objective.***

**NOTE THAT THE PASSING BAR IS HIGHER IN CAPSTONE THAN IT WAS IN PHASE 4!**

#### Exceeds Objective

In addition to completing 100% of the checklist items, goes above and beyond to create a compelling, accessible repository

> Some things to consider doing are running a spell-checker to ensure you don't have typos, adding a description to the repository, using Markdown extensively in the README to create a skim-able document, etc.

> You can also look at the [GitHub tips for post-graduation](https://docs.google.com/document/d/1cT13597jlbiVgKUFyhGC7_QFUrLQUfZViRu8kD_ErAA/edit?usp=sharing) doc (which your career coach will be sending you soon!) to find more examples of enhancements

#### Meets Objective (Passing Bar)

100% of the project checklist items are complete


### Project Motivation

The passing bar for this element will be communicated in the **elevator pitch** portion of the README, immediately after the project title. The elevator pitch should:

* Describe the **data** used in the model
   * This does *not* mean that you should list out every single column name and data type. Instead, describe the data generally.
* Identify the **target**
   * What are you predicting?
* Communicate the **rationale** for predicting this target with this data
   * This can be very brief. The goal is to avoid a "so what?" response
* Evaluate the final model's **performance**

Here are some examples of elevator pitches, which include all of the required elements:

> Searching for skincare products can be overwhelming, since there are so many options and skincare needs vary so much from person to person.  This project uses product and review data scraped from SkinStore.com to make personalized recommendations to a new user based on their skin type, skin problems, and the types of products they're looking for. Using the `surprise` Python package, the final machine learning model has an RMSE of 0.96, meaning that it is able to predict the star rating (out of 5) within 1 star for a given product and user.

> Taxi drivers in New York City have the flexibility to choose when and where to start their workdays, but the best time and location varies. This project uses data about taxi trips from the NYC Open Data portal as well as weather and CitiBike data to forecast demand for taxi pickups across different neighborhoods. The model is able to explain about 70% of the variance in demand and would be especially useful for a taxi company to orchestrate their distribution of resources.

**Note:** There is NO threshold for model performance you are required to meet. So long as you explain what you tried and properly evaluate the outcome, it's fine to have a model with poor performance. We recognize that your time is limited during Capstone and we want you to focus more on the process and communication, not worrying about model performance.

#### Exceeds Objective

Weaves a clear narrative throughout the project explaining the scope, methods, and specific use cases for the final model

#### Meets Objective (Passing Bar)

Describes data, identifies a target, and communicates the rationale for predicting the target with this data and an evaluation of the final model's performance

### Independent Learning

Learning the specific content we teach in the Flatiron School Data Science program is important, but learning how to learn is even more important! This objective is asking you to flex that skill.

The baseline requirement is that you do some domain research, rather than just diving into the dataset. Sometimes a clear understanding of the domain will help you collect a key feature or perform a key preprocessing step that will massively improve your model performance. Work smarter, not harder!

#### Exceeds Objective

Demonstrates a "deep dive" beyond the course content of the DS program, such as extensive domain knowledge or extensively using additional Python packages

> Ideally, your notebook would teach your *instructor* something new about a domain or a technique!

#### Meets Objective (Passing Bar)

Cites at least one external source to demonstrate domain understanding of the project topic

> The source is up to you. It can be an academic whitepaper, an industry publication, a newspaper article, or even just the Wikipedia page on a topic.


### Reproducibility

While you may explore additional forms of *deployment* such as creating an API or web app, the main way that Flatiron School DS projects are deployed is through a reproducible notebook on GitHub.

The explanation of how to reproduce your analysis can either be directly in your README in the Repository Navigation section, or you can create a separate Markdown file and link it in the README.

Be sure to describe the operating system used (including cloud systems such as Kaggle or Google Colab), the packages, and how to get the data.

#### Exceeds Objective

Writes a script so that reproducing the project is seamless on a designated platform

> This can be a Python script or a terminal script. It might involve downloading images and moving them into subfolders, installing packages with `conda` or `pip`, etc.

#### Meets Objective (Passing Bar)

Incorporates the basic elements of a reproducible project: a description of software used + how to get the data

> Ideally you would list the specific versions of packages used through an `environment.yml` or `requirements.txt` file. If you are using a platform like Kaggle, describe the additional `pip install` commands required beyond the base Kaggle environment.

> If your data is proprietary or otherwise not accessible to someone trying to reproduce your analysis, make sure you explain this clearly. If possible, include a sample or anonymized version of the data in the repo.


### Legacy Data Sources
These data sources represent content I found but did not use.

#### Disaster Stats
* International Disaster Database: [EM-Dat](https://www.emdat.be/), [Column Definitions](https://public.emdat.be/about)

#### Refugee Stats
* All the refugee info you could ever want, split any way you want: [UNHCR](https://www.unhcr.org/refugee-statistics/download/)
* More displacement data on refugees [Internal-Displacement](https://www.internal-displacement.org/database/displacement-data)
* A mega dive into the reasoning behind the shocking estimates of future climate refugees: [Migration Data Portal](https://www.migrationdataportal.org/themes/environmental_migration_and_statistics#data-sources)

#### Population Stats
* Population from 1500–2000: [Our World in Data](https://ourworldindata.org/grapher/population-by-country)
* Population from 1950–2021 and future projections: [UN's Website](https://population.un.org/wpp/Download/Standard/MostUsed/), [Dataset](https://population.un.org/wpp/Download/Files/1_Indicators%20(Standard)/EXCEL_FILES/1_General/WPP2022_GEN_F01_DEMOGRAPHIC_INDICATORS_COMPACT_REV1.xlsx)

#### GDP Stats
* GDP from 1820–2018 [Our World in Data](https://ourworldindata.org/grapher/gdp-world-regions-stacked-area)
* GDP from 1960–2021 in 2015 USD [The World Bank](https://data.worldbank.org/indicator/NY.GDP.MKTP.KD)
* GDP growth rates for future years to project GDP past 2021 [International Monetary Fund](https://www.imf.org/external/datamapper/NGDP_RPCH@WEO/OEMDC/ADVEC/WEOWORLD)

#### At-Risk Property Stats
* The total cost, per country, of buildings and machinery at risk of destruction, Produced Capital [CWON 2021 Country Tool (Full Dataset - 219 countries)](https://datacatalog.worldbank.org/search/dataset/0042066)

#### Food Production
* Crop yields under three different climate scenarios: [NASA via Data World](https://data.world/nasa/potential-impacts-of-climate-change-on-world-food-supply-v-1/workspace/file?filename=potential-impacts-world-food-supply.xls)
* Another dataset regarding crop yields: [Kaggle](https://www.kaggle.com/datasets/thedevastator/the-relationship-between-crop-production-and-cli)

#### The 2030 target, keeping with the Paris Agreement
* The Paris Agreement is a legally binding document signed by 186 countries intended to limit global temperature rise to 1.5 °C: [The UN website](https://unfccc.int/process-and-meetings/the-paris-agreement)
  * "The Paris Agreement is a legally binding international treaty on climate change. It was adopted by 196 Parties at the UN Climate Change Conference (COP21) in Paris, France, on 12 December 2015. It entered into force on 4 November 2016.
  
    "Its overarching goal is to hold “the increase in the global average temperature to well below 2°C above pre-industrial levels” and pursue efforts “to limit the temperature increase to 1.5°C above pre-industrial levels.”"
    
* In 2018, the gauntlet was thrown, to cut emissions by 45% from 2010 levels by 2030: [IPCC 2018 Special Report – Global Warming of 1.5 ºC](https://www.ipcc.ch/sr15/chapter/spm/#article-spm-c)
  * "C.1. In model pathways with no or limited overshoot of 1.5°C, global net anthropogenic CO2 emissions decline by about 45% from 2010 levels by 2030 (40–60% interquartile range), reaching net zero around 2050 (2045–2055 interquartile range)."

# Possible Project Directions:

## Show Potential Donors That The Financial Cost of Disaster Mitigation Efforts Will Continue To Rise
### Stakeholder: FEMA? UN Disaster Org? Red Cross?
Plot out all of the climate related disasters of the last 120 years and stress that the pattern and scale are escalating.

## Illustrate Climate Change's Future Effects on the Global Food Supply
### Stakeholder: Hunger NGO? Compassion International? Food For The Hungry?
Show that the already precarious state of food insecurity will reach frightening levels in the near future. Show data along with population increase data.

## Refugee projection for the United States
### Stakeholder: [The Subcommittee on Immigration Integrity, Security, and Enforcement](https://judiciary.house.gov/subcommittees/committee-judiciary/subcommittee-immigration-integrity-security-and-enforcement)
This would be a mix of the disaster statistics and refugee numbers in general. The deeper I dove into this, the more complicated it got. Eventually I found that the IPCC itself admits that the estimating this has been very difficult. If I did this, it would be a stab in the dark based on just the data I listed in the above cell. Mission creep would be extremely tempting with this one.